In [2]:
import json
import pandas as pd
import numpy as np

In [ ]:
# indirect answer identification
ds1 = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/task_1.jsonl", lines=True)
ds1

,pretext,options,correct answer,id
0,Context: X and Y are colleagues who are leavin...,"[Direct answer, Indirect answer]",Direct answer,0
1,Context: X wants to know what activities Y lik...,"[Direct answer, Indirect answer]",Direct answer,1
2,Context: X and Y are childhood neighbours who ...,"[Direct answer, Indirect answer]",Direct answer,2
3,Context: Y has just told X that he/she is cons...,"[Direct answer, Indirect answer]",Indirect answer,3
4,Context: Y has just travelled from a different...,"[Direct answer, Indirect answer]",Indirect answer,4
...,...,...,...,...
2495,Context: Y has just told X that he/she is thin...,"[Direct answer, Indirect answer]",Indirect answer,2495
2496,Context: X wants to know what activities Y lik...,"[Direct answer, Indirect answer]",Direct answer,2496
2497,Context: X wants to know what activities Y lik...,"[Direct answer, Indirect answer]",Indirect answer,2497
2498,Context: X wants to know what activities Y lik...,"[Direct answer, Indirect answer]",Direct answer,2498
2499,Context: X wants to know what activities Y lik...,"[Direct answer, Indirect answer]",Indirect answer,2499

In [10]:
ds1["incorrect"] = ds1["correct answer"].apply(lambda s: "Direct answer" if s == "Indirect answer" else "Indirect answer")
ds1 = ds1.rename({"correct answer": "correct"})

In [ ]:
# ds1['pretext'] = ds1['pretext'].apply(lambda s: s + "\n Is this a direct response or an indirect response?\nThe answer is: ")

'Context: X and Y are colleagues who are leaving work on a Friday at the same time.\nQuestion: Do you want me to give you a lift home?\nResponse: I want me to give I a lift home .\n\n Is this a direct response or an indirect response?\nThe answer is: '

In [16]:
ds1['correct'] = ds1["correct answer"]
ds1.columns

Index(['pretext', 'options', 'correct answer', 'id', 'incorrect', 'correct'], dtype='object')

In [ ]:
# ds1[['pretext', 'correct', 'incorrect']].to_csv("../../behavioral_eval_stimuli/log_p_curated/pub_indirectness-classification.csv", index=False)

In [119]:
# response classification
ds2 = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/task_2.jsonl", lines=True)
ds2

,pretext,options,correct answer,id
0,Context: X and Y are childhood neighbours who ...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,0
1,Context: Y has just moved into a neighbourhood...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,1
2,Context: X wants to know what activities Y lik...,"[Yes, No, Yes, subject to some conditions, In ...",No,2
3,Context: X and Y are colleagues who are leavin...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,3
4,Context: Y has just told X that he/she is cons...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,4
...,...,...,...,...
2501,Context: Y has just moved into a neighbourhood...,"[Yes, No, Yes, subject to some conditions, In ...",No,2501
2502,Context: X and Y are colleagues who are leavin...,"[Yes, No, Yes, subject to some conditions, In ...",No,2502
2503,Context: X and Y are childhood neighbours who ...,"[Yes, No, Yes, subject to some conditions, In ...",No,2503
2504,Context: X wants to know what activities Y lik...,"[Yes, No, Yes, subject to some conditions, In ...","Yes, subject to some conditions",2504
2505,Context: Y has just travelled from a different...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,2505

In [120]:
ds2.loc[0, 
        'pretext']

"Context: X and Y are childhood neighbours who unexpectedly run into each other at a cafe.\nX: Would you like to exchange numbers?\nY: I'll get my contacts open here.\n"

In [110]:
ds2_answers = ["Yes", "No", "Yes, subject to some conditions", 'In the middle, neither yes nor no', "Other"]
print(np.random.choice(list(filter(lambda x: x!= "Yes", ds2_answers))))
print(ds2_answers)

In the middle, neither yes nor no
['Yes', 'No', 'Yes, subject to some conditions', 'In the middle, neither yes nor no', 'Other']

In [121]:
ds2_answers = ["Yes", "No", "Yes, but with some conditions", 'No clear answer, neither yes nor no', "Other"]

In [122]:
ds2 = ds2.rename({"correct answer": "correct"}, axis=1)
ds2["correct"] = ds2["correct"].apply(lambda s: s.replace("Yes, subject to some conditions", "Yes, but with some conditions").replace("In the middle, neither yes nor no", "No clear answer, neither yes nor no"))
def imp_sample_incorrect_answers(row, answer_options):
    correct_answer = row["correct"]
    incorrect_answers = list(filter(lambda x: x != correct_answer, answer_options))
    return incorrect_answers

ds2[[
    "incorrect_1", "incorrect_2", "incorrect_3", "incorrect_4"
]] = pd.DataFrame(ds2.apply(imp_sample_incorrect_answers, axis=1, answer_options=ds2_answers).to_list(), index=ds2.index)
ds2

,pretext,options,correct,id,incorrect_1,incorrect_2,incorrect_3,incorrect_4
0,Context: X and Y are childhood neighbours who ...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,0,No,"Yes, but with some conditions","No clear answer, neither yes nor no",Other
1,Context: Y has just moved into a neighbourhood...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,1,No,"Yes, but with some conditions","No clear answer, neither yes nor no",Other
2,Context: X wants to know what activities Y lik...,"[Yes, No, Yes, subject to some conditions, In ...",No,2,Yes,"Yes, but with some conditions","No clear answer, neither yes nor no",Other
3,Context: X and Y are colleagues who are leavin...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,3,No,"Yes, but with some conditions","No clear answer, neither yes nor no",Other
4,Context: Y has just told X that he/she is cons...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,4,No,"Yes, but with some conditions","No clear answer, neither yes nor no",Other
...,...,...,...,...,...,...,...,...
2501,Context: Y has just moved into a neighbourhood...,"[Yes, No, Yes, subject to some conditions, In ...",No,2501,Yes,"Yes, but with some conditions","No clear answer, neither yes nor no",Other
2502,Context: X and Y are colleagues who are leavin...,"[Yes, No, Yes, subject to some conditions, In ...",No,2502,Yes,"Yes, but with some conditions","No clear answer, neither yes nor no",Other
2503,Context: X and Y are childhood neighbours who ...,"[Yes, No, Yes, subject to some conditions, In ...",No,2503,Yes,"Yes, but with some conditions","No clear answer, neither yes nor no",Other
2504,Context: X wants to know what activities Y lik...,"[Yes, No, Yes, subject to some conditions, In ...","Yes, but with some conditions",2504,Yes,No,"No clear answer, neither yes nor no",Other
2505,Context: Y has just travelled from a different...,"[Yes, No, Yes, subject to some conditions, In ...",Yes,2505,No,"Yes, but with some conditions","No clear answer, neither yes nor no",Other

In [ ]:
# ds2['pretext'] = ds2['pretext'].apply(lambda s: s + "\n Y's response means: ")

In [127]:
# ds2[ds2["incorrect"].isna()]
ds2.columns

Index(['pretext', 'options', 'correct', 'id', 'incorrect_1', 'incorrect_2',
       'incorrect_3', 'incorrect_4'],
      dtype='object')

In [128]:
ds2_subset = ds2[["id", "pretext", "correct", "incorrect_1", "incorrect_2", "incorrect_3", "incorrect_4"]]
# create long format
ds2_subset_long = pd.melt(ds2_subset, id_vars=["id", "pretext", "correct"], value_vars=["incorrect_1", "incorrect_2", "incorrect_3", "incorrect_4"], var_name="incorrect_number", value_name="incorrect")
ds2_subset_long

,id,pretext,correct,incorrect_number,incorrect
0,0,Context: X and Y are childhood neighbours who ...,Yes,incorrect_1,No
1,1,Context: Y has just moved into a neighbourhood...,Yes,incorrect_1,No
2,2,Context: X wants to know what activities Y lik...,No,incorrect_1,Yes
3,3,Context: X and Y are colleagues who are leavin...,Yes,incorrect_1,No
4,4,Context: Y has just told X that he/she is cons...,Yes,incorrect_1,No
...,...,...,...,...,...
10019,2501,Context: Y has just moved into a neighbourhood...,No,incorrect_4,Other
10020,2502,Context: X and Y are colleagues who are leavin...,No,incorrect_4,Other
10021,2503,Context: X and Y are childhood neighbours who ...,No,incorrect_4,Other
10022,2504,Context: X wants to know what activities Y lik...,"Yes, but with some conditions",incorrect_4,Other
10023,2505,Context: Y has just travelled from a different...,Yes,incorrect_4,Other

In [ ]:
# ds2_subset_long.dropna().to_csv("../../behavioral_eval_stimuli/log_p_curated/pub_indirectness_interpretation.csv", index=False)

In [7]:
ds5 = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/task_5.jsonl", lines=True)
ds5

,pretext,options,correct answer,id
0,Speaker_1: The chair was comfortable like a pi...,"[Agrees, Disagrees]",Disagrees,0
1,Speaker_1: the man's idea had the creativity o...,"[Agrees, Disagrees]",Agrees,1
2,Speaker_1: The girl's taste was as rich as cha...,"[Agrees, Disagrees]",Disagrees,2
3,Speaker_1: The student has the insight of a go...,"[Agrees, Disagrees]",Agrees,3
4,Speaker_1: Her eyes are real intoxication.\nSp...,"[Agrees, Disagrees]",Disagrees,4
...,...,...,...,...
1995,Speaker_1: The shirt was as bright as a dark c...,"[Agrees, Disagrees]",Disagrees,1995
1996,Speaker_1: I have the face of a model\nSpeaker...,"[Agrees, Disagrees]",Disagrees,1996
1997,Speaker_1: The chair was comfortable like a pi...,"[Agrees, Disagrees]",Agrees,1997
1998,Speaker_1: The lizard was as ugly as a dead sq...,"[Agrees, Disagrees]",Disagrees,1998
1999,Speaker_1: The cracker was as crunchy as Bitin...,"[Agrees, Disagrees]",Disagrees,1999

In [41]:
ds5.loc[0, 'correct']

'disagrees'

In [43]:
ds5["incorrect"] = ds5["correct answer"].apply(lambda s: "disagrees" if s == "Agrees" else "agrees")
ds5['correct'] = ds5["correct answer"].apply(lambda s: s.lower())
# ds5['pretext'] = ds5['pretext'].apply(lambda s: s + "\n\nDoes speaker 2 agree with speaker 1?\nThe answer is: speaker 2 ")

In [ ]:
# ds5.dropna()[['pretext', 'correct', 'incorrect']].to_csv("../../behavioral_eval_stimuli/log_p_curated/pub_agreement-classification.csv", index=False)

In [49]:
ds6 = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/task_6.jsonl", lines=True)
ds6#.loc[0, 'pretext']

,pretext,options,correct answer,id
0,Speaker_1: The chair was uncomfortable.\nSpeak...,"[Agrees, Sarcastic]",Sarcastic,0
1,Speaker_1: The idea was very creative\nSpeaker...,"[Agrees, Sarcastic]",Agrees,1
2,Speaker_1: The girl had cheap and tacky taste....,"[Agrees, Sarcastic]",Sarcastic,2
3,Speaker_1: The student is unwise\nSpeaker_2: O...,"[Agrees, Sarcastic]",Agrees,3
4,Speaker_1: Her eyes are ugly.\nSpeaker_2: True...,"[Agrees, Sarcastic]",Sarcastic,4
...,...,...,...,...
1995,Speaker_1: The shirt was bright\nSpeaker_2: Of...,"[Agrees, Sarcastic]",Sarcastic,1995
1996,Speaker_1: My face is hideous\nSpeaker_2: True...,"[Agrees, Sarcastic]",Sarcastic,1996
1997,Speaker_1: The chair was very comfortable.\nSp...,"[Agrees, Sarcastic]",Agrees,1997
1998,"Speaker_1: it was cute\nSpeaker_2: True, The l...","[Agrees, Sarcastic]",Sarcastic,1998
1999,Speaker_1: The cracker made loud crunching noi...,"[Agrees, Sarcastic]",Sarcastic,1999

In [ ]:
ds6["incorrect"] = ds6["correct answer"].apply(lambda s: "Yes" if s == "Agrees" else "No")
ds6['correct'] = ds6["correct answer"].apply(lambda s: "Yes" if s == "Sarcastic" else "No")
# ds6['pretext'] = ds6['pretext'].apply(lambda s: s + "\n\nIs speaker 2 being sarcastic with speaker 1? ")

In [ ]:
# ds6.dropna()[['pretext', 'correct', 'incorrect']].to_csv("../../behavioral_eval_stimuli/log_p_curated/pub_sarcasm-classification.csv", index=False)

In [9]:
ds13 = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/task_13.jsonl", lines=True)
ds13

,pretext,options,correct answer,id
0,Conversation:\nSpeaker_1: did you go to the ba...,"[yes, no]",yes,0
1,Conversation:\nSpeaker_1: did you put the cher...,"[yes, no]",no,1
2,Conversation:\nSpeaker_1: are all the bananas ...,"[yes, no]",yes,2
3,Conversation:\nSpeaker_1: was Lucas in the pan...,"[yes, no]",yes,3
4,Conversation:\nSpeaker_1: how many beans are i...,"[yes, no]",no,4
...,...,...,...,...
995,Conversation:\nSpeaker_1: did Nathan go to the...,"[yes, no]",yes,995
996,Conversation:\nSpeaker_1: are all the green pe...,"[yes, no]",no,996
997,Conversation:\nSpeaker_1: how many sweet potat...,"[yes, no]",yes,997
998,Conversation:\nSpeaker_1: did Emily leave the ...,"[yes, no]",yes,998
999,Conversation:\nSpeaker_1: where did Olivia go\...,"[yes, no]",no,999

In [52]:
ds13.loc[0, 'pretext']

"Conversation:\nSpeaker_1: did you go to the basement\nSpeaker_2: I walked to the cellar\nSpeaker_1: did you see the beans\nSpeaker_2: I have no idea\nSpeaker_1: what about the pumpkin\nSpeaker_2: it is in the hallway\nSpeaker_1: did you see the celeries\nSpeaker_2: there is a green pantry in the cellar\nSpeaker_1: did Mason place the celeries there\nSpeaker_2: he placed them there and walked to the hallway\nSpeaker_1: did he put the peaches in the cellar\nSpeaker_2: no, he didn't\nSpeaker_1: did Lily place them in the cellar\nSpeaker_2: no, she didn't\nSpeaker_1: where can I get the melons\nSpeaker_2: there is a red bottle in the cellar\nSpeaker_1: are all of them there\nSpeaker_2: yes\nSpeaker_1: where are the peaches\nSpeaker_2: the peaches are in the basement\nQuestion: are the melons in the cellar?\n"

In [53]:
ds13["incorrect"] = ds13["correct answer"].apply(lambda s: "Yes" if s == "no" else "No")
ds13['correct'] = ds13["correct answer"].apply(lambda s: "Yes" if s == "yes" else "No")

In [ ]:
# ds13.dropna()[['pretext', 'correct', 'incorrect']].to_csv("../../behavioral_eval_stimuli/log_p_curated/pub_deictic-qa.csv", index=False)

Below, manually downloaded SarcV2 datasets are wrangled.

In [4]:
sarc_gen = pd.read_csv("../../../sarcasm_v2/GEN-sarc-notsarc.csv")
sarc_hyp = pd.read_csv("../../../sarcasm_v2/HYP-sarc-notsarc.csv")
sarc_rq = pd.read_csv("../../../sarcasm_v2/RQ-sarc-notsarc.csv")

In [6]:
sarc_gen["incorrect"] = sarc_gen["class"].apply(lambda s: "sarcastic" if s == "notsarc" else "not sarcastic")
sarc_hyp["incorrect"] = sarc_hyp["class"].apply(lambda s: "sarcastic" if s == "notsarc" else "not sarcastic")
sarc_rq["incorrect"] = sarc_rq["class"].apply(lambda s: "sarcastic" if s == "notsarc" else "not sarcastic")

In [7]:
sarc_gen["type"] = "gen"
sarc_hyp["type"] = "hyp"
sarc_rq["type"] = "rq"

In [13]:
sarc_pd = pd.concat([sarc_gen, sarc_hyp, sarc_rq])
sarc_pd

,class,id,text,incorrect,type
0,notsarc,1,"If that's true, then Freedom of Speech is doom...",sarcastic,gen
1,notsarc,2,Neener neener - is it time to go in from the p...,sarcastic,gen
2,notsarc,3,"Just like the plastic gun fear, the armour pie...",sarcastic,gen
3,notsarc,4,So geology is a religion because we weren't he...,sarcastic,gen
4,notsarc,5,Well done Monty. Mark that up as your first ev...,sarcastic,gen
...,...,...,...,...,...
1697,sarc,1698,"Tell me genius, how is me accurately and corre...",not sarcastic,rq
1698,sarc,1699,So you think it is a good idea for public scho...,not sarcastic,rq
1699,sarc,1700,"Now settle down charlie, and try to think rati...",not sarcastic,rq
1700,sarc,1701,The VPC has a political agenda. The FBI? That ...,not sarcastic,rq
1701,sarc,1702,And I didn't. Did you note how I explicitly pu...,not sarcastic,rq

In [16]:
sarc_pd

,class,id,text,incorrect,type,correct
0,notsarc,1,"If that's true, then Freedom of Speech is doom...",sarcastic,gen,not sarcastic
1,notsarc,2,Neener neener - is it time to go in from the p...,sarcastic,gen,not sarcastic
2,notsarc,3,"Just like the plastic gun fear, the armour pie...",sarcastic,gen,not sarcastic
3,notsarc,4,So geology is a religion because we weren't he...,sarcastic,gen,not sarcastic
4,notsarc,5,Well done Monty. Mark that up as your first ev...,sarcastic,gen,not sarcastic
...,...,...,...,...,...,...
1697,sarc,1698,"Tell me genius, how is me accurately and corre...",not sarcastic,rq,sarcastic
1698,sarc,1699,So you think it is a good idea for public scho...,not sarcastic,rq,sarcastic
1699,sarc,1700,"Now settle down charlie, and try to think rati...",not sarcastic,rq,sarcastic
1700,sarc,1701,The VPC has a political agenda. The FBI? That ...,not sarcastic,rq,sarcastic
1701,sarc,1702,And I didn't. Did you note how I explicitly pu...,not sarcastic,rq,sarcastic

In [ ]:
sarc_pd["correct"] = sarc_pd["class"].apply(lambda s: "sarcastic" if s == "sarc" else "not sarcastic")
# sarc_pd["text"] = sarc_pd["text"].apply(lambda s: s + "\n\nWas this paragraph sarcastic or not?\n\nThe paragraph was " )

In [ ]:
# sarc_pd[["id", "text", "incorrect", "correct", "type"]].reset_index().to_csv("../../behavioral_eval_stimuli/log_p_curated/sarcv2.csv", index=False)

## EmoBench dataset

In [43]:
emo_ea = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/EA.jsonl", lines=True)
emo_ea_en = emo_ea[emo_ea["language"] == "en"]

In [44]:
emo_eu = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/EU.jsonl", lines=True)
emo_eu_en = emo_eu[emo_eu["language"] == "en"]

In [45]:
emo_ea_en.loc[0, "choices"]
emo_ea_en

,qid,language,category,question type,scenario,subject,choices,label
0,1,en,Personal-Others,Action,Sarah found out that her younger brother is be...,Sarah,"[Promise to keep the secret, Inform their pare...",Suggest her brother to talk to a teacher or a ...
1,2,en,Personal-Others,Action,Natalie's friend has recently been going throu...,Natalie,[Cut off communication with her friend for a w...,Suggest her friend to seek professional help l...
2,3,en,Personal-Others,Action,James' best friend has been acting distant and...,James,"[Pray for his friend's wellbeing, Confront his...",Respect his friend's privacy but express his w...
3,4,en,Personal-Others,Action,Mike's teenage son was caught yesterday steali...,Mike,"[Pay the owner, hoping it's a one-time mistake...",Arrange a meeting with the store owner for his...
4,5,en,Personal-Others,Action,Samantha's teenage daughter recently started h...,Samantha,"[Forbid her from seeing these friends, Persona...",Discuss her concerns with her daughter
...,...,...,...,...,...,...,...,...
195,196,en,Social-Self,Response,Karen was working when her manager called her ...,Karen,"[""This is not fair, I need hours to pay my bil...","""I understand, is there any way that I can pic..."
196,197,en,Social-Self,Response,"After a project meeting, the TA pulled Ian asi...",Ian,"[""Thank you for your comments However, I think...","""Thank you for your comments However, I think ..."
197,198,en,Social-Self,Response,Frank and his team gave the proposal presentat...,Frank,"[""We appreciate your feedback, is there any ch...","""We appreciate your feedback, is there any cha..."
198,199,en,Social-Self,Response,Kyle practiced his project plan with his labma...,Kyle,"[""Thanks for your input. If anyone else has fe...","""Thank you for your feedback. Our earlier disc..."
199,200,en,Social-Self,Response,Matt decided to participate in a hackathon. Ho...,Matt,"[""Hey, could you guys cover the parts I'm resp...","""I'm so sorry, I've been really busy with othe..."

In [46]:
emo_eu_en

,qid,language,coarse_category,finegrained_category,scenario,subject,emotion_choices,emotion_label,cause_choices,cause_label
0,1,en,complex_emotions,emotion_transition,Dorea was trying to cook a Baklava. When she t...,Dorea,"[Delight, Anger, Embarrassment, Hopeless, Prid...",Delight,"[Her daughter tried to make her feel better, d...",Her daughter enjoyed the Baklava despite it be...
1,2,en,complex_emotions,emotion_transition,"Simon, an amateur painter, had been working on...",Simon,"[Delight, Anger, Embarrassment, Hopeless, Prid...",Delight,[He thought he had painted the perfect portrai...,His wife appreciated his effort and liked his ...
2,3,en,complex_emotions,emotion_transition,"After weeks of hard work and determination, An...",Andy,"[Gratitude & Anger, Embarrassment & Joy, Sadne...",Gratitude & Joy,"[Nobody from work showed up, His boss showed u...",His boss showed up and praised his work
3,4,en,complex_emotions,emotion_transition,Albert and his dad made a deal. If Albert mana...,Albert,"[Jealousy, Embarrassment, Nervousness, Delight...",Delight,"[He proved his father right, His father was go...",Because one of the top 5 contestants cheated a...
4,5,en,complex_emotions,emotion_transition,Momo loved dancing and used it as an escape fr...,Momo,"[Relief, Sadness, Anger, Hopeless, Amusement, ...",Relief,"[She got praised by her boss, She was able to ...",She was able to dance away her frustration and...
...,...,...,...,...,...,...,...,...,...,...
195,196,en,perspective_taking,false_belief,Michael has been working hard to perfect a new...,Michael,"[Disappointment, Excitement, Pride, Anticipati...",Disappointment,[Lily knew every part of his magic trick that ...,Lily knew every part of his magic trick that h...
196,197,en,perspective_taking,false_belief,Michael has been working hard to perfect a new...,Lily,"[Guilt, Excitement, Pride, Surprise, Gratitude...",Excitement,"[She loves magic tricks, She made Michael feel...",She made Michael feel like she got the trick w...
197,198,en,perspective_taking,false_belief,"My sister, Janet, has been waiting for her lov...",Janet,"[Excitement, Disappointment, Annoyance, Embarr...",Excitement,[She overheard Daniel talking about his nervou...,She knows Daniel is going to ask her to prom
198,199,en,perspective_taking,false_belief,"My sister, Janet, has been waiting for her lov...",Daniel,"[Anticipation, Sadness, Gratitude, Sentimental...",Anticipation,[He knows his prom date will accept his reques...,He knows his prom date will accept his request
199,200,en,perspective_taking,false_belief,"My sister, Janet, has been waiting for her lov...",I,"[Nervousness, Joy, Disapproval, Disgust, Grati...",Nervousness,[My sister is going out with the guy she likes...,I don't know how to tell my sister that Daniel...

In [47]:
emo_eu_en["question_emotion"] = emo_eu_en["subject"].apply(lambda s: f"What emotion would {s} feel in this situation? The choices are: ")
emo_eu_en["question_cause"] = emo_eu_en.apply(lambda r: f"Why would {r['subject']} feel {r['emotion_label']} in this situation?", axis=1)

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/3579438881.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en["question_emotion"] = emo_eu_en["subject"].apply(lambda s: f"What emotion would {s} feel in this situation? The choices are: ")
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/3579438881.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en["question_cause"] = emo_eu_en.apply(lambda r: f"Why would {r['subject']} feel {r['emotion_label']} in this situation?", axis=1)

In [ ]:
def get_incorrect_option(row, correct_col="emotion_label", options_col="emotion_choices"):
    correct = row[correct_col]
    options = row[options_col]
    incorrect_option = list(filter(lambda x: x!= correct, options))
    if correct_col == "cause_label":
        incorrect_option = np.random.choice(incorrect_option, size=3, replace=False)
        return incorrect_option
    return incorrect_option

In [33]:
emo_eu_en

,qid,language,coarse_category,finegrained_category,scenario,subject,emotion_choices,emotion_label,cause_choices,cause_label,question_emotion,question_cause
0,1,en,complex_emotions,emotion_transition,Dorea was trying to cook a Baklava. When she t...,Dorea,"[Delight, Anger, Embarrassment, Hopeless, Prid...",Delight,"[Her daughter tried to make her feel better, d...",Her daughter enjoyed the Baklava despite it be...,What emotion would Dorea feel in this situation?,Why would Dorea feel Delight in this situation?
1,2,en,complex_emotions,emotion_transition,"Simon, an amateur painter, had been working on...",Simon,"[Delight, Anger, Embarrassment, Hopeless, Prid...",Delight,[He thought he had painted the perfect portrai...,His wife appreciated his effort and liked his ...,What emotion would Simon feel in this situation?,Why would Simon feel Delight in this situation?
2,3,en,complex_emotions,emotion_transition,"After weeks of hard work and determination, An...",Andy,"[Gratitude & Anger, Embarrassment & Joy, Sadne...",Gratitude & Joy,"[Nobody from work showed up, His boss showed u...",His boss showed up and praised his work,What emotion would Andy feel in this situation?,Why would Andy feel Gratitude & Joy in this si...
3,4,en,complex_emotions,emotion_transition,Albert and his dad made a deal. If Albert mana...,Albert,"[Jealousy, Embarrassment, Nervousness, Delight...",Delight,"[He proved his father right, His father was go...",Because one of the top 5 contestants cheated a...,What emotion would Albert feel in this situation?,Why would Albert feel Delight in this situation?
4,5,en,complex_emotions,emotion_transition,Momo loved dancing and used it as an escape fr...,Momo,"[Relief, Sadness, Anger, Hopeless, Amusement, ...",Relief,"[She got praised by her boss, She was able to ...",She was able to dance away her frustration and...,What emotion would Momo feel in this situation?,Why would Momo feel Relief in this situation?
...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,en,perspective_taking,false_belief,Michael has been working hard to perfect a new...,Michael,"[Disappointment, Excitement, Pride, Anticipati...",Disappointment,[Lily knew every part of his magic trick that ...,Lily knew every part of his magic trick that h...,What emotion would Michael feel in this situat...,Why would Michael feel Disappointment in this ...
196,197,en,perspective_taking,false_belief,Michael has been working hard to perfect a new...,Lily,"[Guilt, Excitement, Pride, Surprise, Gratitude...",Excitement,"[She loves magic tricks, She made Michael feel...",She made Michael feel like she got the trick w...,What emotion would Lily feel in this situation?,Why would Lily feel Excitement in this situation?
197,198,en,perspective_taking,false_belief,"My sister, Janet, has been waiting for her lov...",Janet,"[Excitement, Disappointment, Annoyance, Embarr...",Excitement,[She overheard Daniel talking about his nervou...,She knows Daniel is going to ask her to prom,What emotion would Janet feel in this situation?,Why would Janet feel Excitement in this situat...
198,199,en,perspective_taking,false_belief,"My sister, Janet, has been waiting for her lov...",Daniel,"[Anticipation, Sadness, Gratitude, Sentimental...",Anticipation,[He knows his prom date will accept his reques...,He knows his prom date will accept his request,What emotion would Daniel feel in this situation?,Why would Daniel feel Anticipation in this sit...
199,200,en,perspective_taking,false_belief,"My sister, Janet, has been waiting for her lov...",I,"[Nervousness, Joy, Disapproval, Disgust, Grati...",Nervousness,[My sister is going out with the guy she likes...,I don't know how to tell my sister that Daniel...,What emotion would I feel in this situation?,Why would I feel Nervousness in this situation?

In [ ]:
# we will just shuffle and take the first three incorrect labels for cause
emo_eu_en.loc[16, "cause_choices"]
emo_eu_en["num_cause_choices"] = emo_eu_en["cause_choices"].apply(len)
emo_eu_en["num_cause_choices"].value_counts()

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/856652705.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en["num_cause_choices"] = emo_eu_en["cause_choices"].apply(len)

num_cause_choices
4    140
6     60
Name: count, dtype: int64

In [57]:
emo_eu_en[[
    "incorrect_emotion_1", "incorrect_emotion_2", "incorrect_emotion_3", "incorrect_emotion_4", "incorrect_emotion_5"
]] = pd.DataFrame(emo_eu_en.apply(get_incorrect_option, axis=1, correct_col="emotion_label", options_col="emotion_choices").to_list(), index=emo_eu_en.index)

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1151798261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1151798261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1151798261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1151798261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1151798261.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en[[

In [59]:
emo_eu_en_emotion = emo_eu_en[["qid", "scenario", "question_emotion", "emotion_label", "incorrect_emotion_1", "incorrect_emotion_2", "incorrect_emotion_3", "incorrect_emotion_4", "incorrect_emotion_5"]]

In [70]:
emo_eu_en[[
    "incorrect_cause_1", "incorrect_cause_2", "incorrect_cause_3"
]] = pd.DataFrame(emo_eu_en.apply(get_incorrect_option, axis=1, correct_col="cause_label", options_col="cause_choices").to_list(), index=emo_eu_en.index)

correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices
correct col,  cause_label cause_choices

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/2391952351.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/2391952351.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/2391952351.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en[[

In [71]:
emo_eu_en_cause = emo_eu_en[["qid", "scenario", "question_cause", "cause_label", "incorrect_cause_1", "incorrect_cause_2", "incorrect_cause_3"]]

In [86]:
def create_choices_prompt(row, correct, incorrect_options):
    # TODO: create options in randomized order, make sure to record which one is the correct one (with the numbered prefix)
    options = [row[correct]] + [row[opt] for opt in incorrect_options]
    np.random.shuffle(options)
    correct_index = options.index(row[correct]) + 1
    options_prompt = "Choices:\n" + "\n".join([f"{i+1}. {opt}" for i, opt in enumerate(options)])
    # get the incorrect options only
    incorrect_prompt = options_prompt.replace(f"{correct_index}. {row[correct]}", "").replace("Choices:\n", "").strip()
    incorrect_options_processed = [o for o in incorrect_prompt.split("\n") if len(o.strip()) > 0]
    return options_prompt, f"{correct_index}. {row[correct]}", incorrect_options_processed

In [ ]:
emo_eu_en_emotion[[
    "emotion_choices_prompt",
    "emotion_correct",
    "incorrect_emotions_processed"
]] = pd.DataFrame(emo_eu_en_emotion.apply(create_choices_prompt, axis=1, correct="emotion_label", incorrect_options=["incorrect_emotion_1", "incorrect_emotion_2", "incorrect_emotion_3", "incorrect_emotion_4", "incorrect_emotion_5"]).to_list(), index=emo_eu_en_emotion.index)

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1703291010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en_emotion[[

In [88]:
# spread the incorrect emotions into separate columns
emo_eu_en_emotion_wide = emo_eu_en_emotion.copy()
for i in range(5):
    emo_eu_en_emotion_wide[f"incorrect_emotion_{i+1}_processed"] = emo_eu_en_emotion_wide["incorrect_emotions_processed"].apply(lambda s: s[i] if len(s) > i else None) 

emo_eu_en_emotion_wide

,qid,scenario,question_emotion,emotion_label,incorrect_emotion_1,incorrect_emotion_2,incorrect_emotion_3,incorrect_emotion_4,incorrect_emotion_5,emotion_choices_prompt,emotion_correct,incorrect_emotions_processed,incorrect_emotion_1_processed,incorrect_emotion_2_processed,incorrect_emotion_3_processed,incorrect_emotion_4_processed,incorrect_emotion_5_processed
0,1,Dorea was trying to cook a Baklava. When she t...,What emotion would Dorea feel in this situatio...,Delight,Anger,Embarrassment,Hopeless,Pride,Disappointment,Choices:\n1. Anger\n2. Hopeless\n3. Pride\n4. ...,5. Delight,"[1. Anger, 2. Hopeless, 3. Pride, 4. Embarrass...",1. Anger,2. Hopeless,3. Pride,4. Embarrassment,6. Disappointment
1,2,"Simon, an amateur painter, had been working on...",What emotion would Simon feel in this situatio...,Delight,Anger,Embarrassment,Hopeless,Pride,Disappointment,Choices:\n1. Hopeless\n2. Anger\n3. Pride\n4. ...,4. Delight,"[1. Hopeless, 2. Anger, 3. Pride, 5. Disappoin...",1. Hopeless,2. Anger,3. Pride,5. Disappointment,6. Embarrassment
2,3,"After weeks of hard work and determination, An...",What emotion would Andy feel in this situation...,Gratitude & Joy,Gratitude & Anger,Embarrassment & Joy,Sadness & Anger,Embarrassment & Sadness,Embarrassment & Anger,Choices:\n1. Gratitude & Joy\n2. Sadness & Ang...,1. Gratitude & Joy,"[2. Sadness & Anger, 3. Embarrassment & Joy, 4...",2. Sadness & Anger,3. Embarrassment & Joy,4. Gratitude & Anger,5. Embarrassment & Sadness,6. Embarrassment & Anger
3,4,Albert and his dad made a deal. If Albert mana...,What emotion would Albert feel in this situati...,Delight,Jealousy,Embarrassment,Nervousness,Disapproval,Guilt,Choices:\n1. Nervousness\n2. Disapproval\n3. J...,6. Delight,"[1. Nervousness, 2. Disapproval, 3. Jealousy, ...",1. Nervousness,2. Disapproval,3. Jealousy,4. Embarrassment,5. Guilt
4,5,Momo loved dancing and used it as an escape fr...,What emotion would Momo feel in this situation...,Relief,Sadness,Anger,Hopeless,Amusement,Guilt,Choices:\n1. Guilt\n2. Amusement\n3. Anger\n4....,4. Relief,"[1. Guilt, 2. Amusement, 3. Anger, 5. Hopeless...",1. Guilt,2. Amusement,3. Anger,5. Hopeless,6. Sadness
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,Michael has been working hard to perfect a new...,What emotion would Michael feel in this situat...,Disappointment,Excitement,Pride,Anticipation,Gratitude,Anger,Choices:\n1. Anger\n2. Anticipation\n3. Disapp...,3. Disappointment,"[1. Anger, 2. Anticipation, 4. Pride, 5. Excit...",1. Anger,2. Anticipation,4. Pride,5. Excitement,6. Gratitude
196,197,Michael has been working hard to perfect a new...,What emotion would Lily feel in this situation...,Excitement,Guilt,Pride,Surprise,Gratitude,Curiosity,Choices:\n1. Pride\n2. Gratitude\n3. Surprise\...,6. Excitement,"[1. Pride, 2. Gratitude, 3. Surprise, 4. Guilt...",1. Pride,2. Gratitude,3. Surprise,4. Guilt,5. Curiosity
197,198,"My sister, Janet, has been waiting for her lov...",What emotion would Janet feel in this situatio...,Excitement,Disappointment,Annoyance,Embarrassment,Nervousness,Sadness,Choices:\n1. Embarrassment\n2. Annoyance\n3. S...,4. Excitement,"[1. Embarrassment, 2. Annoyance, 3. Sadness, 5...",1. Embarrassment,2. Annoyance,3. Sadness,5. Nervousness,6. Disappointment
198,199,"My sister, Janet, has been waiting for her lov...",What emotion would Daniel feel in this situati...,Anticipation,Sadness,Gratitude,Sentimental,Embarrassment,Guilt,Choices:\n1. Embarrassment\n2. Sentimental\n3....,5. Anticipation,"[1. Embarrassment, 2. Sentimental, 3. Guilt, 4...",1. Embarrassment,2. Sentimental,3. Guilt,4. Sadness,6. Gratitude
199,200,"My sister, Janet, has been waiting for her lov...",What emotion would I feel in this situation? T...,Nervousness,Joy,Disapproval,Disgust,Gratitude,Annoyance,Choices:\n1. Annoyance\n2. Disapproval\n3. Ner...,3. Nervousness,"[1. Annoyance, 2. Disapproval, 4. Joy, 5. Disg...",1. Annoyance,2. Disapproval,4. Joy,5. Disgust,6. Gratitude

In [90]:
emo_eu_en_emotion_wide_subset = emo_eu_en_emotion_wide[[
    "qid", "scenario", "question_emotion", "emotion_correct", "emotion_choices_prompt", "incorrect_emotion_1_processed", "incorrect_emotion_2_processed", "incorrect_emotion_3_processed", "incorrect_emotion_4_processed", "incorrect_emotion_5_processed"
]]
emo_eu_en_emotion_long = emo_eu_en_emotion_wide_subset.melt(
    id_vars=["qid", "scenario", "question_emotion", "emotion_correct", "emotion_choices_prompt"], value_vars=["incorrect_emotion_1_processed", "incorrect_emotion_2_processed", "incorrect_emotion_3_processed", "incorrect_emotion_4_processed", "incorrect_emotion_5_processed"], var_name="incorrect_option_num", value_name="incorrect_option")
emo_eu_en_emotion_long

,qid,scenario,question_emotion,emotion_correct,emotion_choices_prompt,incorrect_option_num,incorrect_option
0,1,Dorea was trying to cook a Baklava. When she t...,What emotion would Dorea feel in this situatio...,5. Delight,Choices:\n1. Anger\n2. Hopeless\n3. Pride\n4. ...,incorrect_emotion_1_processed,1. Anger
1,2,"Simon, an amateur painter, had been working on...",What emotion would Simon feel in this situatio...,4. Delight,Choices:\n1. Hopeless\n2. Anger\n3. Pride\n4. ...,incorrect_emotion_1_processed,1. Hopeless
2,3,"After weeks of hard work and determination, An...",What emotion would Andy feel in this situation...,1. Gratitude & Joy,Choices:\n1. Gratitude & Joy\n2. Sadness & Ang...,incorrect_emotion_1_processed,2. Sadness & Anger
3,4,Albert and his dad made a deal. If Albert mana...,What emotion would Albert feel in this situati...,6. Delight,Choices:\n1. Nervousness\n2. Disapproval\n3. J...,incorrect_emotion_1_processed,1. Nervousness
4,5,Momo loved dancing and used it as an escape fr...,What emotion would Momo feel in this situation...,4. Relief,Choices:\n1. Guilt\n2. Amusement\n3. Anger\n4....,incorrect_emotion_1_processed,1. Guilt
...,...,...,...,...,...,...,...
995,196,Michael has been working hard to perfect a new...,What emotion would Michael feel in this situat...,3. Disappointment,Choices:\n1. Anger\n2. Anticipation\n3. Disapp...,incorrect_emotion_5_processed,6. Gratitude
996,197,Michael has been working hard to perfect a new...,What emotion would Lily feel in this situation...,6. Excitement,Choices:\n1. Pride\n2. Gratitude\n3. Surprise\...,incorrect_emotion_5_processed,5. Curiosity
997,198,"My sister, Janet, has been waiting for her lov...",What emotion would Janet feel in this situatio...,4. Excitement,Choices:\n1. Embarrassment\n2. Annoyance\n3. S...,incorrect_emotion_5_processed,6. Disappointment
998,199,"My sister, Janet, has been waiting for her lov...",What emotion would Daniel feel in this situati...,5. Anticipation,Choices:\n1. Embarrassment\n2. Sentimental\n3....,incorrect_emotion_5_processed,6. Gratitude
999,200,"My sister, Janet, has been waiting for her lov...",What emotion would I feel in this situation? T...,3. Nervousness,Choices:\n1. Annoyance\n2. Disapproval\n3. Ner...,incorrect_emotion_5_processed,6. Gratitude

In [ ]:
# emo_eu_en_emotion_long.to_csv("../../behavioral_eval_stimuli/log_p_curated/emobench_understanding_emotion.csv", index=False)

In [ ]:
# now the same processing is applied to the cause questions
emo_eu_en_cause[[
    "cause_choices_prompt",
    "cause_correct",
    "incorrect_causes_processed"
]] = pd.DataFrame(emo_eu_en_cause.apply(create_choices_prompt, axis=1, correct="cause_label", incorrect_options=["incorrect_cause_1", "incorrect_cause_2", "incorrect_cause_3"]).to_list(), index=emo_eu_en_cause.index)

# spread the incorrect emotions into separate columns
emo_eu_en_cause_wide = emo_eu_en_cause.copy()
for i in range(3):
    emo_eu_en_cause_wide[f"incorrect_cause_{i+1}_processed"] = emo_eu_en_cause_wide["incorrect_causes_processed"].apply(lambda s: s[i] if len(s) > i else None)

print(emo_eu_en_cause_wide.head())


emo_eu_en_cause_wide_subset = emo_eu_en_cause_wide[[
    "qid", "scenario", "question_cause", "cause_correct", "cause_choices_prompt", "incorrect_cause_1_processed", "incorrect_cause_2_processed", "incorrect_cause_3_processed"
]]
emo_eu_en_cause_long = emo_eu_en_cause_wide_subset.melt(
    id_vars=["qid", "scenario", "question_cause", "cause_correct", "cause_choices_prompt"], value_vars=["incorrect_cause_1_processed", "incorrect_cause_2_processed", "incorrect_cause_3_processed"], var_name="incorrect_option_num", value_name="incorrect_option")
emo_eu_en_cause_long

   qid                                           scenario  \
0    1  Dorea was trying to cook a Baklava. When she t...
1    2  Simon, an amateur painter, had been working on...
2    3  After weeks of hard work and determination, An...
3    4  Albert and his dad made a deal. If Albert mana...
4    5  Momo loved dancing and used it as an escape fr...

                                      question_cause  \
0    Why would Dorea feel Delight in this situation?
1    Why would Simon feel Delight in this situation?
2  Why would Andy feel Gratitude & Joy in this si...
3   Why would Albert feel Delight in this situation?
4      Why would Momo feel Relief in this situation?

                                         cause_label  \
0  Her daughter enjoyed the Baklava despite it be...
1  His wife appreciated his effort and liked his ...
2            His boss showed up and praised his work
3  Because one of the top 5 contestants cheated a...
4  She was able to dance away her frustration and...

                                incorrect_cause_1  \
0                      The Baklava was not ruined
1  He made a mistake in a painting he cared about
2                 He didn't like his own drawings
3                       He was named in the top 6
4                     She got praised by her boss

                                  incorrect_cause_2  \
0                    Her daughter just arrived home
1    He thought he had painted the perfect portrait
2                His coworkers disliked his artwork
3      His father was going to buy him a new laptop
4  Her client accepted her work after many changes.

                                   incorrect_cause_3  \
0  Her daughter tried to make her feel better, de...
1  His wife appreciated his effort despite notici...
2                         Nobody from work showed up
3                         He proved his father right
4     She finally satisfied her client's expectation

                                cause_choices_prompt  \
0  Choices:\n1. Her daughter enjoyed the Baklava ...
1  Choices:\n1. His wife appreciated his effort d...
2  Choices:\n1. His coworkers disliked his artwor...
3  Choices:\n1. His father was going to buy him a...
4  Choices:\n1. Her client accepted her work afte...

                                       cause_correct  \
0  1. Her daughter enjoyed the Baklava despite it...
1  3. His wife appreciated his effort and liked h...
2         2. His boss showed up and praised his work
3  4. Because one of the top 5 contestants cheate...
4  2. She was able to dance away her frustration ...

                          incorrect_causes_processed  \
0  [2. Her daughter just arrived home, 3. Her dau...
1  [1. His wife appreciated his effort despite no...
2  [1. His coworkers disliked his artwork, 3. He ...
3  [1. His father was going to buy him a new lapt...
4  [1. Her client accepted her work after many ch...

                         incorrect_cause_1_processed  \
0                  2. Her daughter just arrived home
1  1. His wife appreciated his effort despite not...
2              1. His coworkers disliked his artwork
3    1. His father was going to buy him a new laptop
4  1. Her client accepted her work after many cha...

                         incorrect_cause_2_processed  \
0  3. Her daughter tried to make her feel better,...
1  2. He thought he had painted the perfect portrait
2                 3. He didn't like his own drawings
3                       2. He was named in the top 6
4                     3. She got praised by her boss

                         incorrect_cause_3_processed
0                      4. The Baklava was not ruined
1  4. He made a mistake in a painting he cared about
2                      4. Nobody from work showed up
3                      3. He proved his father right
4  4. She finally satisfied her client's expectation

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1255120202.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en_cause[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1255120202.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en_cause[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1255120202.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_eu_en_cause[[

,qid,scenario,question_cause,cause_correct,cause_choices_prompt,incorrect_option_num,incorrect_option
0,1,Dorea was trying to cook a Baklava. When she t...,Why would Dorea feel Delight in this situation?,1. Her daughter enjoyed the Baklava despite it...,Choices:\n1. Her daughter enjoyed the Baklava ...,incorrect_cause_1_processed,2. Her daughter just arrived home
1,2,"Simon, an amateur painter, had been working on...",Why would Simon feel Delight in this situation?,3. His wife appreciated his effort and liked h...,Choices:\n1. His wife appreciated his effort d...,incorrect_cause_1_processed,1. His wife appreciated his effort despite not...
2,3,"After weeks of hard work and determination, An...",Why would Andy feel Gratitude & Joy in this si...,2. His boss showed up and praised his work,Choices:\n1. His coworkers disliked his artwor...,incorrect_cause_1_processed,1. His coworkers disliked his artwork
3,4,Albert and his dad made a deal. If Albert mana...,Why would Albert feel Delight in this situation?,4. Because one of the top 5 contestants cheate...,Choices:\n1. His father was going to buy him a...,incorrect_cause_1_processed,1. His father was going to buy him a new laptop
4,5,Momo loved dancing and used it as an escape fr...,Why would Momo feel Relief in this situation?,2. She was able to dance away her frustration ...,Choices:\n1. Her client accepted her work afte...,incorrect_cause_1_processed,1. Her client accepted her work after many cha...
...,...,...,...,...,...,...,...
595,196,Michael has been working hard to perfect a new...,Why would Michael feel Disappointment in this ...,3. Lily knew every part of his magic trick tha...,Choices:\n1. He performed his magic trick as p...,incorrect_cause_3_processed,4. He forgot how he planned the magic trick
596,197,Michael has been working hard to perfect a new...,Why would Lily feel Excitement in this situation?,4. She made Michael feel like she got the tric...,Choices:\n1. She feels bad for ruining Michael...,incorrect_cause_3_processed,3. She is not impressed by Michael's skills
597,198,"My sister, Janet, has been waiting for her lov...",Why would Janet feel Excitement in this situat...,1. She knows Daniel is going to ask her to prom,Choices:\n1. She knows Daniel is going to ask ...,incorrect_cause_3_processed,4. Janet's friends told her that Daniel would ...
598,199,"My sister, Janet, has been waiting for her lov...",Why would Daniel feel Anticipation in this sit...,1. He knows his prom date will accept his request,Choices:\n1. He knows his prom date will accep...,incorrect_cause_3_processed,4. He knows he will be rejected if he asks Janet
599,200,"My sister, Janet, has been waiting for her lov...",Why would I feel Nervousness in this situation?,4. I don't know how to tell my sister that Dan...,Choices:\n1. I wanted to take Lisa to the prom...,incorrect_cause_3_processed,3. My sister is going out with the guy she likes

In [ ]:
# emo_eu_en_cause_long.to_csv("../../behavioral_eval_stimuli/log_p_curated/emobench_understanding_cause.csv", index=False)

In [96]:
emo_ea_en

,qid,language,category,question type,scenario,subject,choices,label
0,1,en,Personal-Others,Action,Sarah found out that her younger brother is be...,Sarah,"[Promise to keep the secret, Inform their pare...",Suggest her brother to talk to a teacher or a ...
1,2,en,Personal-Others,Action,Natalie's friend has recently been going throu...,Natalie,[Cut off communication with her friend for a w...,Suggest her friend to seek professional help l...
2,3,en,Personal-Others,Action,James' best friend has been acting distant and...,James,"[Pray for his friend's wellbeing, Confront his...",Respect his friend's privacy but express his w...
3,4,en,Personal-Others,Action,Mike's teenage son was caught yesterday steali...,Mike,"[Pay the owner, hoping it's a one-time mistake...",Arrange a meeting with the store owner for his...
4,5,en,Personal-Others,Action,Samantha's teenage daughter recently started h...,Samantha,"[Forbid her from seeing these friends, Persona...",Discuss her concerns with her daughter
...,...,...,...,...,...,...,...,...
195,196,en,Social-Self,Response,Karen was working when her manager called her ...,Karen,"[""This is not fair, I need hours to pay my bil...","""I understand, is there any way that I can pic..."
196,197,en,Social-Self,Response,"After a project meeting, the TA pulled Ian asi...",Ian,"[""Thank you for your comments However, I think...","""Thank you for your comments However, I think ..."
197,198,en,Social-Self,Response,Frank and his team gave the proposal presentat...,Frank,"[""We appreciate your feedback, is there any ch...","""We appreciate your feedback, is there any cha..."
198,199,en,Social-Self,Response,Kyle practiced his project plan with his labma...,Kyle,"[""Thanks for your input. If anyone else has fe...","""Thank you for your feedback. Our earlier disc..."
199,200,en,Social-Self,Response,Matt decided to participate in a hackathon. Ho...,Matt,"[""Hey, could you guys cover the parts I'm resp...","""I'm so sorry, I've been really busy with othe..."

In [97]:
# now process the application part
emo_ea_en["question_application"] = emo_ea_en.apply(lambda r: f"What would be the most effective {r['question type'].lower()} for {r['subject']} in this situation?", axis=1)

emo_ea_en[[
    "incorrect_action_1", "incorrect_action_2", "incorrect_action_3"
]] = pd.DataFrame(emo_ea_en.apply(get_incorrect_option, axis=1, correct_col="label", options_col="choices").to_list(), index=emo_ea_en.index)

emo_ea_en[[
    "action_choices_prompt",
    "action_correct",
    "incorrect_actions_processed"
]] = pd.DataFrame(emo_ea_en.apply(create_choices_prompt, axis=1, correct="label", incorrect_options=["incorrect_action_1", "incorrect_action_2", "incorrect_action_3"]).to_list(), index=emo_ea_en.index)

# spread the incorrect emotions into separate columns
emo_ea_en_wide = emo_ea_en.copy()
for i in range(3):
    emo_ea_en_wide[f"incorrect_action_{i+1}_processed"] = emo_ea_en_wide["incorrect_actions_processed"].apply(lambda s: s[i] if len(s) > i else None)

print(emo_ea_en_wide.head())


emo_ea_en_wide_subset = emo_ea_en_wide[[
    "qid", "scenario", "question_application", "action_correct", "action_choices_prompt", "incorrect_action_1_processed", "incorrect_action_2_processed", "incorrect_action_3_processed"
]]
emo_ea_en_wide_long = emo_ea_en_wide_subset.melt(
    id_vars=["qid", "scenario", "question_application", "action_correct", "action_choices_prompt"], value_vars=["incorrect_action_1_processed", "incorrect_action_2_processed", "incorrect_action_3_processed"], var_name="incorrect_option_num", value_name="incorrect_option")
emo_ea_en_wide_long

correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
correct col,  label choices
   qid language         category question type  \
0    1       en  Personal-Others        Action
1    2       en  Personal-Others        Action
2    3       en  Personal-Others        Action
3    4       en  Personal-Others        Action
4    5       en  Personal-Others        Action

                                            scenario   subject  \
0  Sarah found out that her younger brother is be...     Sarah
1  Natalie's friend has recently been going throu...   Natalie
2  James' best friend has been acting distant and...     James
3  Mike's teenage son was caught yesterday steali...      Mike
4  Samantha's teenage daughter recently started h...  Samantha

                                             choices  \
0  [Promise to keep the secret, Inform their pare...
1  [Cut off communication with her friend for a w...
2  [Pray for his friend's wellbeing, Confront his...
3  [Pay the owner, hoping it's a one-time mistake...
4  [Forbid her from seeing these friends, Persona...

                                               label  \
0  Suggest her brother to talk to a teacher or a ...
1  Suggest her friend to seek professional help l...
2  Respect his friend's privacy but express his w...
3  Arrange a meeting with the store owner for his...
4             Discuss her concerns with her daughter

                                question_application  \
0  What would be the most effective action for Sa...
1  What would be the most effective action for Na...
2  What would be the most effective action for Ja...
3  What would be the most effective action for Mi...
4  What would be the most effective action for Sa...

                                  incorrect_action_1  \
0                         Promise to keep the secret
1  Cut off communication with her friend for a while
2                    Pray for his friend's wellbeing
3      Pay the owner, hoping it's a one-time mistake
4               Forbid her from seeing these friends

                                  incorrect_action_2  \
0                        Inform their parents anyway
1  Continuously reassure her friend that everythi...
2      Confront his friend for not being transparent
3        Call the police to report his son's actions
4            Personally meet and talk to her friends

                                  incorrect_action_3  \
0                       Confront the bullies herself
1            Tell her friend to deal with it herself
2  Offer to help with whatever the personal probl...
3       Ground his son without discussing the issue.
4           Invite these friends over to their house

                               action_choices_prompt  \
0  Choices:\n1. Promise to keep the secret\n2. Co...
1  Choices:\n1. Suggest her friend to seek profes...
2  Choices:\n1. Confront his friend for not being...
3  Choices:\n1. Arrange a meeting with the store ...
4  Choices:\n1. Personally meet and talk to her f...

                                      action_correct  \
0  3. Suggest her brother to talk to a teacher or...
1  1. Suggest her friend to seek professional hel...
2  2. Respect his friend's privacy but express hi...
3  1. Arrange a meeting with the store owner for ...
4          4. Discuss her concerns with her daughter

                         incorrect_actions_processed  \
0  [1. Promise to keep the secret, 2. Confront th...
1  [2. Tell her friend to deal with it herself, 3...
2  [1. Confront his friend for not being transpar...
3  [2. Ground his son without discussing the issu...
4  [1. Personally meet and talk to her friends, 2...

                       incorrect_action_1_processed  \
0                     1. Promise to keep the secret
1        2. Tell her friend to deal with it herself
2  1. Confront his friend for not being transparent
3   2. Ground his son without discussing the issue.
4        1. Personally meet and talk to her friends

                        incorrect_action_2_processed  \
0                    2. Confront the bullies herself
1  3. Continuously reassure her friend that every...
2                 3. Pray for his friend's wellbeing
3     3. Call the police to report his son's actions
4        2. Invite these friends over to their house

                        incorrect_action_3_processed
0                     4. Inform their parents anyway
1  4. Cut off communication with her friend for a...
2  4. Offer to help with whatever the personal pr...
3   4. Pay the owner, hoping it's a one-time mistake
4            3. Forbid her from seeing these friends

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/507672302.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_ea_en["question_application"] = emo_ea_en.apply(lambda r: f"What would be the most effective {r['question type'].lower()} for {r['subject']} in this situation?", axis=1)
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/507672302.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_ea_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/507672302.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_ea_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/507672302.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_ea_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/507672302.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_ea_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/507672302.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_ea_en[[
/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/507672302.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  emo_ea_en[[

,qid,scenario,question_application,action_correct,action_choices_prompt,incorrect_option_num,incorrect_option
0,1,Sarah found out that her younger brother is be...,What would be the most effective action for Sa...,3. Suggest her brother to talk to a teacher or...,Choices:\n1. Promise to keep the secret\n2. Co...,incorrect_action_1_processed,1. Promise to keep the secret
1,2,Natalie's friend has recently been going throu...,What would be the most effective action for Na...,1. Suggest her friend to seek professional hel...,Choices:\n1. Suggest her friend to seek profes...,incorrect_action_1_processed,2. Tell her friend to deal with it herself
2,3,James' best friend has been acting distant and...,What would be the most effective action for Ja...,2. Respect his friend's privacy but express hi...,Choices:\n1. Confront his friend for not being...,incorrect_action_1_processed,1. Confront his friend for not being transparent
3,4,Mike's teenage son was caught yesterday steali...,What would be the most effective action for Mi...,1. Arrange a meeting with the store owner for ...,Choices:\n1. Arrange a meeting with the store ...,incorrect_action_1_processed,2. Ground his son without discussing the issue.
4,5,Samantha's teenage daughter recently started h...,What would be the most effective action for Sa...,4. Discuss her concerns with her daughter,Choices:\n1. Personally meet and talk to her f...,incorrect_action_1_processed,1. Personally meet and talk to her friends
...,...,...,...,...,...,...,...
595,196,Karen was working when her manager called her ...,What would be the most effective response for ...,"4. ""I understand, is there any way that I can ...","Choices:\n1. ""Thank you for the notice, but is...",incorrect_action_3_processed,"3. ""This is not fair, I need hours to pay my b..."
596,197,"After a project meeting, the TA pulled Ian asi...",What would be the most effective response for ...,"3. ""Thank you for your comments However, I thi...","Choices:\n1. ""I see! I appreciate your input I...",incorrect_action_3_processed,"4. ""Oh, thank you for giving your insights. Fo..."
597,198,Frank and his team gave the proposal presentat...,What would be the most effective response for ...,"3. ""We appreciate your feedback, is there any ...","Choices:\n1. ""Can we ask for feedback from a p...",incorrect_action_3_processed,"4. ""Thank you, we really appreciate your feedb..."
598,199,Kyle practiced his project plan with his labma...,What would be the most effective response for ...,"3. ""Thank you for your feedback. Our earlier d...","Choices:\n1. ""Thanks for your input. If anyone...",incorrect_action_3_processed,"4. ""I appreciate your feedback. Can we discuss..."
599,200,Matt decided to participate in a hackathon. Ho...,What would be the most effective response for ...,"4. ""I'm so sorry, I've been really busy with o...","Choices:\n1. ""I have prioritized the other pro...",incorrect_action_3_processed,"3. ""I can just join another team if you guys f..."

In [ ]:
# emo_ea_en_wide_long.to_csv("../../behavioral_eval_stimuli/log_p_curated/emobench_application.csv", index=False)

## Social IQA

In [1]:
# preprocess social IQA into a long format, akin to the OpenToM_attitude dataset
from datasets import load_dataset
siqa = load_dataset("allenai/social_i_qa")
siqa_df = siqa['validation'].to_pandas()

README.md: 0.00B [00:00, ?B/s]

social_i_qa.py: 0.00B [00:00, ?B/s]

Downloading data:   0%|          | 0.00/2.20M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/33410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1954 [00:00<?, ? examples/s]

In [101]:
siqa_df.loc[669]

context        Tracy enjoyed constructing things and made a t...
question                         How would she feel as a result?
answerA                                             accomplished
answerB                                             accomplished
answerC                                                    proud
label                                                          1
correct                                             accomplished
incorrect_1                                                proud
incorrect_2                                                 None
Name: 669, dtype: object

In [9]:
answer_options = ["answerA", "answerB", "answerC"]
siqa_df["correct"] = siqa_df.apply(lambda row: row[answer_options[int(row["label"])-1]], axis=1)

In [ ]:
# create columns incorrect 1 and incorrect 2
def sample_incorrect_answers(row, answer_options):
    correct_answer = row["correct"]
    incorrect_answers = list(filter(lambda x: x != correct_answer, [row[opt] for opt in answer_options]))
    return incorrect_answers


siqa_df[[
    "incorrect_1", "incorrect_2"
]] = pd.DataFrame(siqa_df.apply(sample_incorrect_answers, axis=1, answer_options=answer_options).to_list(), index=siqa_df.index)

In [14]:
# remove unused columns
siqa_df_subset = siqa_df[["context", "question", "correct", "incorrect_1", "incorrect_2"]]
# add a numeric id column
siqa_df_subset["id"] = siqa_df_subset.index

# create long format
siqa_long = pd.melt(siqa_df_subset, id_vars=["id", "context", "question", "correct"], value_vars=["incorrect_1", "incorrect_2"], var_name="incorrect_number", value_name="incorrect")
siqa_long

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_61101/1128031723.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  siqa_df_subset["id"] = siqa_df_subset.index

,id,context,question,correct,incorrect_number,incorrect
0,0,Tracy didn't go home that evening and resisted...,What does Tracy need to do before this?,Find somewhere to go,incorrect_1,make a new plan
1,1,Sydney walked past a homeless woman asking for...,How would you describe Sydney?,sympathetic,incorrect_1,like a person who was unable to help
2,2,Sasha protected the patients' rights by making...,What will patients want to do next?,get petitions signed,incorrect_1,write new laws
3,3,Jordan was in charge of taking the food on the...,How would Jordan feel afterwards?,horrible that he let his friends down on the c...,incorrect_1,happy that he doesn't need to do the cooking o...
4,4,Kendall opened their mouth to speak and what c...,How would you describe Kendall?,a very aggressive and talkative person,incorrect_1,a very quiet person
...,...,...,...,...,...,...
3903,1949,Bailey destroyed the enemy's bunker and won th...,What does Bailey need to do before this?,spy on enemy troop movements,incorrect_2,win the war for his country
3904,1950,Kai told Kendall the reason about the accident...,How would you describe Kai?,like they got something off their chest,incorrect_2,feeling sad
3905,1951,Kai improved Jan's picture and she loved how i...,What will Jan want to do next?,frame the picture,incorrect_2,wanted to Jan to be glad
3906,1952,Tracy's kids wanted ice cream so Aubrey fed th...,What does Aubrey need to do before this?,get ice cream,incorrect_2,thanks Aubrey
3907,1953,Aubrey the officer pulled a driver over for sp...,Why did Aubrey do this?,so people don't drive to fast,incorrect_2,look up the person's license plate number

In [ ]:
# siqa_long.to_csv("../../behavioral_eval_stimuli/log_p_curated/social_iqa.csv", index=False)

In [149]:
# process imppress, as provided in PUB
imp_impl = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/task_10.jsonl", lines=True)
imp_impl

,pretext,options,correct answer,id
0,Premise: Amy could prevent Stephen from hiding...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,0
1,Premise: That tomato needed to fall.\nHypothes...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,1
2,Premise: Rebecca needed to research banks.\nHy...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,2
3,Premise: Timothy could like to fall asleep.\nH...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,3
4,Premise: Those men didn't need to fall asleep....,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,4
...,...,...,...,...
2095,Premise: No people had questioned Steven.\nHyp...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,2095
2096,Premise: Not all organizations induced Jane's ...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,2096
2097,Premise: No actors will predict many blouses t...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,2097
2098,Premise: No cashiers had concealed David.\nHyp...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,2098
2099,Premise: All gloves should loosen.\nHypothesis...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,2099

In [150]:
imp_impl_answers = ["The hypothesis follows from the premise.", "The hypothesis contradicts the premise.", "The hypothesis is in no clear relationship with the premise."]
imp_impl = imp_impl.rename({"correct answer": "correct"}, axis=1)

def imp_sample_incorrect_answers(row, answer_options):
    correct_answer = row["correct"]
    incorrect_answers = list(filter(lambda x: x != correct_answer, answer_options))
    return incorrect_answers

imp_impl["correct"] = imp_impl["correct"].apply(lambda s: s.replace("Hypothesis is definitely true given premise", "The hypothesis follows from the premise.").replace("Hypothesis is definitely not true given premise", "The hypothesis contradicts the premise.").replace("Hypothesis might be true given premise", "The hypothesis is in no clear relationship with the premise."))
# imp_impl["correct"].unique()
imp_impl[[
    "incorrect_1", "incorrect_2"
]] = pd.DataFrame(imp_impl.apply(imp_sample_incorrect_answers, axis=1, answer_options=imp_impl_answers).to_list(), index=imp_impl.index)

In [ ]:
imppres_question = "\nWhat is the relationship between the premise and the hypothesis? "

# imp_impl["pretext"] = imp_impl.apply(lambda r: r["pretext"] + imppres_question, axis=1)

In [152]:
imp_impl_subset = imp_impl[["id", "pretext", "correct", "incorrect_1", "incorrect_2"]]
# create long format
imp_impl_long = pd.melt(imp_impl_subset, id_vars=["id", "pretext", "correct"], value_vars=["incorrect_1", "incorrect_2"], var_name="incorrect_number", value_name="incorrect")

In [ ]:
# imp_impl_long.to_csv("../../behavioral_eval_stimuli/log_p_curated/imppres_implicature.csv", index=False)

In [154]:
# process imppress, as provided in PUB
imp_pre = pd.read_json(path_or_buf="../../behavioral_eval_stimuli/task_11.jsonl", lines=True)
imp_pre

,pretext,options,correct answer,id
0,Premise: Natalie hasn't discovered where Tracy...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,0
1,Premise: If April forgot where that hat did tw...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,1
2,Premise: If the teachers forget about where Th...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,2
3,Premise: Rebecca might have investigated how t...,"[Hypothesis is definitely true given premise, ...",Hypothesis might be true given premise,3
4,Premise: That committee might forget where Kir...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,4
...,...,...,...,...
1795,Premise: Grace might have fallen.\nHypothesis:...,"[Hypothesis is definitely true given premise, ...",Hypothesis might be true given premise,1795
1796,"Premise: If Patricia has climbed up the steps,...","[Hypothesis is definitely true given premise, ...",Hypothesis might be true given premise,1796
1797,Premise: Travis does hire Alexander.\nHypothes...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,1797
1798,Premise: The cucumber had ripened.\nHypothesis...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely true given premise,1798
1799,Premise: Adam might wake up.\nHypothesis: Adam...,"[Hypothesis is definitely true given premise, ...",Hypothesis is definitely not true given premise,1799

In [155]:
imp_pre.loc[0, "pretext"]
imp_pre_answers = ["The hypothesis follows from the premise.", "The hypothesis contradicts the premise.", "The hypothesis is in no clear relationship with the premise."]
imp_pre = imp_pre.rename({"correct answer": "correct"}, axis=1)
imp_pre["correct"] = imp_pre["correct"].apply(lambda s: s.replace("Hypothesis is definitely true given premise", "The hypothesis follows from the premise.").replace("Hypothesis is definitely not true given premise", "The hypothesis contradicts the premise.").replace("Hypothesis might be true given premise", "The hypothesis is in no clear relationship with the premise."))

imp_pre[[
    "incorrect_1", "incorrect_2"
]] = pd.DataFrame(imp_pre.apply(imp_sample_incorrect_answers, axis=1, answer_options=imp_pre_answers).to_list(), index=imp_pre.index)

In [ ]:
imppres_question = "\nWhat is the relationship between the premise and the hypothesis? "

# imp_pre["pretext"] = imp_pre.apply(lambda r: r["pretext"] + imppres_question, axis=1)

In [157]:
imp_pre_subset = imp_pre[["id", "pretext", "correct", "incorrect_1", "incorrect_2"]]
# create long format
imp_pre_long = pd.melt(imp_pre_subset, id_vars=["id", "pretext", "correct"], value_vars=["incorrect_1", "incorrect_2"], var_name="incorrect_number", value_name="incorrect")

In [ ]:
# imp_pre_long.to_csv("../../behavioral_eval_stimuli/log_p_curated/imppres_presupposition.csv", index=False)

### Preprocessing ToMi from Sap et al

This is the source for the data used by AlKhamissi et al for their ToMi evals: http://maartensap.com/neuralToM/ToMi-finalNeuralTOM.csv

Below, it is wrangled into a format compatible with our eval script.

In [2]:
import pandas as pd
tomi_raw = pd.read_csv("../../../ToMi-finalNeuralTOM.csv")

In [9]:
tomi_first_order = tomi_raw[tomi_raw["qOrder"] == "first_order"]
tomi_first_order["incorrect"] = tomi_first_order.apply(lambda r: r["cands"].replace(str(r["answer"]), "").replace('"', '').replace("[", "").replace("]", "").strip().strip(","), axis=1)
tomi_first_order = tomi_first_order.rename({"answer": "correct"}, axis=1)

/var/folders/fn/6ct_6l112376k8288ws7798m0000gn/T/ipykernel_36795/841694330.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tomi_first_order["incorrect"] = tomi_first_order.apply(lambda r: r["cands"].replace(str(r["answer"]), "").replace('"', '').replace("[", "").replace("]", "").strip().strip(","), axis=1)

In [10]:
len(tomi_first_order)
tomi_first_order

,story,question,correct,i,dataGenSeq,sType,qTypeRaw,qTypeTomOrNot,qOrder,storyHasToM,answerMem,answerReal,qToMandOmniReader,answerMemOrReal,cands,correct,falseTrueBelief,factVsMind,incorrect
2,Jack entered the laundry. Logan entered the st...,Where will Jack look for the persimmon?,bucket,1,"enter_agent_0,agent_2_enters,enter_agent_1,age...",second_order_false_belief,first_order_0_no_tom,False,first_order,False,pantry,bucket,False,reality,"[""pantry"", ""bucket""]",1,True,mind,pantry
4,Ella entered the dining room. Carter entered t...,Where will Ella look for the lemon?,drawer,1,"enter_agent_1,enter_agent_0,agent_1_exits,agen...",false_belief,first_order_0_tom,True,first_order,True,drawer,pantry,False,memory,"[""pantry"", ""drawer""]",1,False,mind,pantry
5,Mason entered the bedroom. Isabella entered th...,Where will Mason look for the pineapple?,crate,1,"enter_agent_0,enter_agent_1,agent_2_enters,age...",second_order_false_belief,first_order_0_no_tom,False,first_order,False,bottle,crate,False,reality,"[""bottle"", ""crate""]",1,True,mind,bottle
7,Mason entered the sunroom. Ella entered the su...,Where will Mason look for the lemon?,bottle,1,"enter_agent_0,enter_agent_1,agent_1_exits,agen...",false_belief,first_order_0_no_tom,False,first_order,False,bathtub,bottle,False,reality,"[""bottle"", ""bathtub""]",0,True,mind,bathtub
10,Alexander entered the garden. James entered th...,Where will Avery look for the boots?,container,1,"agent_2_enters,enter_agent_0,agent_2_exits,ent...",true_belief,first_order_1_no_tom,False,first_order,False,basket,container,False,reality,"[""container"", ""basket""]",0,True,mind,basket
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1853,Oliver entered the laundry. Aiden dislikes the...,Where will Oliver look for the peach?,suitcase,1,"enter_agent_1,enter_agent_0,agent_1_exits,agen...",true_belief,first_order_0_no_tom,False,first_order,False,drawer,suitcase,False,reality,"[""drawer"", ""suitcase""]",1,True,mind,drawer
1854,James dislikes the t-shirt. Aria entered the b...,Where will Hannah look for the pumpkin?,box,1,"enter_agent_0,agent_2_enters,enter_agent_1,age...",false_belief,first_order_1_tom,True,first_order,True,box,bathtub,False,memory,"[""bathtub"", ""box""]",1,False,mind,bathtub
1855,Chloe entered the back yard. Amelia entered th...,Where will Chloe look for the underclothes?,suitcase,1,"enter_agent_1,enter_agent_0,agent_1_exits,agen...",second_order_false_belief,first_order_0_tom,True,first_order,True,suitcase,pantry,False,memory,"[""suitcase"", ""pantry""]",0,False,mind,pantry
1856,Jackson entered the cellar. Noah entered the c...,Where will Jackson look for the onion?,envelope,1,"enter_agent_1,enter_agent_0,agent_1_exits,agen...",false_belief,first_order_0_tom,True,first_order,True,envelope,bathtub,False,memory,"[""bathtub"", ""envelope""]",1,False,mind,bathtub
1859,Benjamin entered the office. Sophia entered th...,Where will Sophia look for the plum?,envelope,1,"enter_agent_1,enter_agent_0,agent_0_moves_obj,...",true_belief,first_order_1_no_tom,False,first_order,False,drawer,envelope,False,reality,"[""drawer"", ""envelope""]",1,True,mind,drawer

In [ ]:
tomi_first_order_subset = tomi_first_order[["story", "question", "correct", "incorrect"]]
# tomi_first_order_subset.to_csv("../../behavioral_eval_stimuli/log_p_curated/tomi_sapEtAl_first_order.csv", index=False)

### Prepare additional baseline datasets

In [3]:
from datasets import load_dataset
snli = load_dataset("stanfordnlp/snli", split="test")

README.md: 0.00B [00:00, ?B/s]

test-00000-of-00001.parquet:   0%|          | 0.00/412k [00:00<?, ?B/s]

validation-00000-of-00001.parquet:   0%|          | 0.00/413k [00:00<?, ?B/s]

train-00000-of-00001.parquet:   0%|          | 0.00/19.6M [00:00<?, ?B/s]

Generating test split:   0%|          | 0/10000 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/10000 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/550152 [00:00<?, ? examples/s]

In [33]:
# because impres tasks were also NLI tasks, here for SNLI we use the exact same formatting
# sample same size as Blimp subset, 670 datapoints
snli_question = "\nWhat is the relationship between the premise and the hypothesis? "
template = """Premise: {premise}
Hypothesis: {hypothesis}
What is the relationship between the premise and the hypothesis?"""
option_mapping = {
    0: "The hypothesis follows from the premise.",
    1: "The hypothesis is in no clear relationship with the premise.",
    2: "The hypothesis contradicts the premise."
}

In [34]:
snli_sample = snli.filter(lambda x: x["label"] != -1).select(range(670)).to_pandas()

In [35]:
snli_sample["pretext"] = snli_sample.apply(lambda x: template.format(premise=x["premise"], hypothesis=x["hypothesis"]), axis=1)

In [36]:
snli_sample["correct"] = snli_sample["label"].map(option_mapping)
snli_sample

,premise,hypothesis,label,pretext,correct
0,This church choir sings to the masses as they ...,The church has cracks in the ceiling.,1,Premise: This church choir sings to the masses...,The hypothesis is in no clear relationship wit...
1,This church choir sings to the masses as they ...,The church is filled with song.,0,Premise: This church choir sings to the masses...,The hypothesis follows from the premise.
2,This church choir sings to the masses as they ...,A choir singing at a baseball game.,2,Premise: This church choir sings to the masses...,The hypothesis contradicts the premise.
3,"A woman with a green headscarf, blue shirt and...",The woman is young.,1,"Premise: A woman with a green headscarf, blue ...",The hypothesis is in no clear relationship wit...
4,"A woman with a green headscarf, blue shirt and...",The woman is very happy.,0,"Premise: A woman with a green headscarf, blue ...",The hypothesis follows from the premise.
...,...,...,...,...,...
665,Man holding torch of fire.,The man is holding a bag.,2,Premise: Man holding torch of fire.\nHypothesi...,The hypothesis contradicts the premise.
666,Man holding torch of fire.,There is a man.,0,Premise: Man holding torch of fire.\nHypothesi...,The hypothesis follows from the premise.
667,Man holding torch of fire.,The fire is large.,1,Premise: Man holding torch of fire.\nHypothesi...,The hypothesis is in no clear relationship wit...
668,Villagers pulling in the fish boat.,The villagers are preparing to go fishing.,1,Premise: Villagers pulling in the fish boat.\n...,The hypothesis is in no clear relationship wit...
669,Villagers pulling in the fish boat.,The villagers are sitting around the camp fire.,2,Premise: Villagers pulling in the fish boat.\n...,The hypothesis contradicts the premise.

In [37]:
def snli_sample_incorrect_answers(row, answer_options):
    correct_answer = row["correct"]
    incorrect_answers = list(filter(lambda x: x != correct_answer, answer_options))
    return incorrect_answers

In [38]:
snli_sample[[
    "incorrect_1", "incorrect_2"
]] = pd.DataFrame(snli_sample.apply(snli_sample_incorrect_answers, axis=1, answer_options=option_mapping.values()).to_list(), index=snli_sample.index)
snli_sample_subset = snli_sample[["pretext", "correct", "incorrect_1", "incorrect_2"]]
# create long format
snli_sample_long = pd.melt(snli_sample_subset, id_vars=["pretext", "correct"], value_vars=["incorrect_1", "incorrect_2"], var_name="incorrect_number", value_name="incorrect")

In [ ]:
# snli_sample_long.to_csv("../../behavioral_eval_stimuli/log_p_curated/snli.csv", index=False)

In [ ]:
# construct verbal analogies datasets from Webb et al
### story analogies ###
# Load problems
import numpy as np
import builtins
import time
df = pd.read_excel (r'../../../Public/Cognitive Psychology.xlsx', sheet_name='Rattermann')
source_story = builtins.list(df['Base'])[1:19]
true_analogy = builtins.list(df['True Analogy Story'])[1:19]
false_analogy = builtins.list(df['False Analogy Story'])[1:19]
literal_similarity = builtins.list(df['Literally similar story'])[1:19]
mere_appearance = builtins.list(df['Mere-Appearance Match'])[1:19]
N_source_stories = 18
story_analogies_stories = []
story_analogies_correct = []
story_analogies_incorrect = []
for s in range(N_source_stories):
	print('Source story ' + str(s+1) + ' of ' + str(N_source_stories) + '...')
	# A. True analogy B. False analogy
	print('True analogy vs. false analogy')
	# shuffle order in the context
	if np.random.rand() < 0.5:
		stories = [true_analogy[s], false_analogy[s]]
		answer_options = ['Story A', 'Story B']
	else:
		stories = [false_analogy[s], true_analogy[s]]
		answer_options = ['Story B', 'Story A']
	print(' ')
	prompt = 'Consider the following story:\n\nStory 1: ' + source_story[s] + '\n\nNow consider two more stories:\n\nStory A: ' + stories[0] + '\n\nStory B: ' + stories[1] + '\n\n'
	prompt += 'Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?'
	print(prompt)
	story_analogies_stories.append(prompt)
	story_analogies_correct.append(answer_options[0])
	story_analogies_incorrect.append(answer_options[1])

# create csv
story_analogies_df = pd.DataFrame({
    'pretext': story_analogies_stories,
    'correct': story_analogies_correct,
    'incorrect': story_analogies_incorrect
})
# story_analogies_df.to_csv('../../behavioral_eval_stimuli/log_p_curated/story_analogies.csv', index=False)

Source story 1 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1: William was a patient in a psychiatric hospital who was confined indoors almost all the time. He could never pass the monthly room inspections so he hated them. He spent most of his time daydreaming about food.
A few day before the April inspection William's room was still a mess since he had done nothing but daydream. To provide William with an incentive, the nurse promised him some gingerbread from the cookie shop if he scrubbed his room and put it in order once and for all.
William was overjoyed. But there was no longer enough time for him to put it in order. As a result, he did not pass the inspection and did not get any gingerbread.
William sulked all day and slammed his door so hard the plaster cracked, but he still didn't get any gingerbread.

Now consider two more stories:

Story A: Karen always did poorly in high school so she despised it. But she loved vacations. She spent most of her time dreaming about going to Hawaii.
Not long before the end of her fourth year Karen was not doing at all well in her classes because she had spent all her time daydreaming. To motivate her, Karen's father promised her that if she did well enough during the next few weeks to graduate from high school he would pay for her trip to Hawaii.
This made Karen extremely happy. But she was too far behind in her classes. Consequently she failed too many and did not go to Hawaii.


Story B: Karen disliked high school so she always had trouble getting passing grades in her classes. Vacations were her favorite part of the school year.
Not long before the end of her fourth year of school, Karen was not doing well at all because she despised school. To motivate her, Karen's father promised her a trip to Hawaii if she would just pass enough of her classes to graduate.
This made Karen extremely happy. During the last few weeks of school she spent most of her time dreaming about Hawaii and preparing for her trip there. Consequently, she failed to graduate and she did not get to go.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 2 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1: Mr. Newton was the manager of a company that made razors. One year, an inventor in his company perfected a metal that would stay sharper than any previous razor.
However, not long after that, Mr. Newton was using one of these new razors and he cut his neck rather severely. As a result of this incident the inventor recommended a safety feature that would protect people from injuring themselves.
After what had happened, Mr. Newton considered the safety feature absolutely necessary. The incident had alarmed him so much that he began to produce the safety razor right away. Luckily, his neck did not get infected so everything was alright.

Now consider two more stories:

Story A: Ms. Boyce was in charge of installing sun lamps sold by Smith Tan Company. In 1980, a supplier for the company perfected a filament that could produce more intense heat than any previous filament. Because it was so hot, the supplier recommended a warning label that would protect people from hurting themselves with the new lamp.
But Mrs. Boyce considered the labels unnecessary. It would be too much trouble to make them.
But later, when she was using one of these new heat lamps herself, she was seriously burned. After this accident she was so frightened that she had the warning labels printed immediately.

Story B: Ms. Boyce was in charge of installing heat lamps sold by the Smith Tan Company. In 1980, a supplier for the company perfected a filament that could produce more intense heat than any previous filament.
But later, when Ms. Boyce was using one of these new heat lamps herself she was seriously burned. Because of this accident the supplier recommended a warning label that would protect people from hurting themselves with the new lamp.
After this, Ms. Boyce considered the labels absolutely necessary. The accident frightened her so much that she had the labels printed immediately.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 3 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1: Joseph was a millionaire who hired a chauffeur to drive his Rolls-Royce. He used to brag. to his wife that he would never be late for his conferences since he had hired a chauffeur.
One morning when he was in a great hurry, he went to find the chauffeur. But he was asleep. He thought his services would not be needed that day.
Thus Joseph was very late for his conference after all. To make sure this would not happen again, Joseph hired a second chauffeur. This turned out to be very expensive because the second chauffeur wanted a fancy uniform as well as a high salary.

Now consider two more stories:

Story A: Many years ago there was man named Alexander who had two wives living in two houses: He liked to boast to a friend that with his two wives he would always eat well.
One day when he was very hungry, Alexander went to his first wife. But she had only prepared enough for herself and their baby. She thought Alexander would eat with his other wife that day.
Alexander then went to his second wife, but found she had already finished. She saw him go to the other house so she thought he was eating there.
Thus Alexander went without any dinner at all.

Story B: Alexander was a man who lived with his wife in his house a long time ago. He liked to boast to a friend that with his wife at home he would always eat well.
One day, when he was very hungry, Alexander went home to his wife. But she thought Alexander would be eating someplace else so she had only prepared enough for herself and their baby.
Thus Alexander went without dinner. But to make sure he would not go hungry again, Alexander married a second wife.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 4 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1: Karla, an old hawk, lived at the top of a tall oak tree.  One afternoon, she saw a hunter on the ground with a bow and some crude arrows that had no feathers.   The hunter took aim and shot at the hawk but missed.  Karla knew the hunter wanted her feathers so she glided down to the hunter and offered to give him a few.  The hunter was so grateful that he pledged never to shoot at a hawk again.  He went off and shot deer instead.

Now consider two more stories:

Story A: Once there was a small country called Zerdia that learned to make the world's smartest computer. One day Zerdia was attacked by its warlike neighbor, Gagrach.  But the missiles were badly aimed and the attack failed.  The Zerdian government realized that Gagrach wanted Zerdian computers so it offered to sell some of its computers to the country.  The government of Gagrach was very pleased.  It promised never to attack Zerdia again.

Story B: Once there was a small country called Zerdia that learned to make the world's smartest computer.  Zerdia sold one of itssupercomputers to its neighbor, Gagrach, so Gagrach would promise never to attack Zerdia. But one day Zerdia was overwhelmed by a surprise attack from Gagrach.  As it capitulated the crippled government of Zerdia realized that the attacker's missiles had been guided by Zerdian supercomputers.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 5 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1: Peter was a young man from Iceland who moved to Florida one summer. He was very self-conscious about his fair skin. Peter thought that people would not accept him unless he tanned himself golden-brown like every one else.
So Peter spent a whole day in the sun, trying to get a tan. He didn't understand how dangerous the sun could be. Consequently, by evening he had second degree burns over most of his body and he had to go to the hospital. Peter decided that Florida was not for him and booked the next ocean liner back to Iceland. He spent the whole trip under a large umbrella keeping cool.

Now consider two more stories:

Story A: Quiggly Company was a small company that manufactured conventional electrical components. They had just started producing integrated circuits and decided that the real action in the integrated circuit market was in space manufacturing. But the market analysts gave them a stern warning. They said that space factories were too expensive and that the market was too competitive. If Quiggly went into space manufacturing, the analysts predicted they would lose everything and their stock would plunge.
Quiggly Company was so annoyed at having to play it safe when everyone else had a chance to make a killing that they decided to go back to manufacturing conventional electric components.

Story B: Quiggly Company was as small company that manufactured electrical components. One, year, Quiggly Co. began to get into the integrated circuit market. However, Quiggly Company felt that to be competitive it would have to have really sophisticated space factories, as did all the other manufacturers of integrated circuits. Thus, Quiggly put all its assets into having a space factory. The company just didn't realize what a financial risk space manufacturing was. As a result, within six months, Quiggly Company had spent much more than they could afford and their stocks plunged to an all time low. .Quiggly Co. decided to pull out of integrated circuits altogether and went back to making conventional electrical components.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 6 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1:      Julius was a mule who discovered several pears sitting in a window sill.  He thought to himself, "These pears seem to be rotten.  Perhaps I'll get some and find out if my prediction is correct."
     However, the pears were too high for Julius.  And because he was hungry he felt too weak to jump up to them.  Naturally, this was rather disappointing.  He closed his eyes and went to sleep, dreaming about mountains of pears.

Now consider two more stories:

Story A:      A girl named Cindy found some records she was curious about at a record store.   "These records look really bad,"  Cindy thought to herself.  "I think I'll buy them so I can see if my hunch is right."
     But, the records were too expensive for her.  After thinking it over, she saw there was no way she could afford them.  Needless to say, she became somewhat disappointed.

Story B:      A girl named Cindy found some records she wanted at a record store.  She really wanted them but, needless to say, they were too expensive for her.
     After brooding for awhile, Cindy got over her dissapointment.
     "These records are probably boring," she thought.  "So even if I could afford them I wouldn't listen to them."

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 7 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1:      Percy the mockingbird spent the whole warm season chirping and twittering.  When it began to get colder Percy visited a squirrel and sang a song for her, expecting to get some of the squirrel's sunflower seeds in return.  However, the squirrel was very disappointed in him.
     "You are a terrible singer!" she yelled.  "I'm not giving you any of my wheat."
     A tear  rolled down Percy's cheek, and he vowed to give up singing for good.

Now consider two more stories:

Story A:      Sam travelled all over the world buying beautiful things.  When he ran out of money he paid a visit to his mother and gave her a gift he bought while in Tibet, hoping she would give him a loan in return.  However, his mother was not at all pleased.
     "You don't deserve any money of mine!" she exclaimed.  "This is a piece of junk!"

Story B:      Sam travelled all over the world buying beautiful things.  When he ran out of money he paid a visit to his mother.  However, she was not at all pleased with him.
     "While I have been hard at work you have been wasting your time," she said.  Sam gave her a gift he bought in Tibet, hoping she would give him a loan in return.  But she was still not pleased.  "I will not give you any of my hard-earned money!" she exclaimed.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 8 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1: A dog named Leonard was trotting along a dock holding a steak in his teeth. However, as he trotted he dropped it inadvertently and it disappeared into the lake. Thus, he was left without his dinner.
Then Leonard saw another dog with a steak. Because he had lost his own steak he tried to take it. Unluckily, the other dog was much bigger than he was. Leonard ended up losing a tooth in the scuffle.

Now consider two more stories:

Story A: Charlie was walking through a hotel with an expensive pocket watch in his hand. Then he noticed another man with an expensive watch.
Not realizing it was just his reflection, and since he was also quite greedy, Charlie reached out to take it. Unfortunately, as he opened his hand he dropped his own watch and both watches shattered on the floor. Consequently he was left with no watch at all.

Story B: Charlie was walking through a hotel with an expensive pocket watch in his hand. As he walked he accidently dropped it and it shattered on the floor. Consequently, he was left without a watch.
Then Charlie saw another man with an expensive watch. Since he had broken his own watch he reached out to take it. Unfortunately, the man was a policeman.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 9 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1: Boris and Ivan thought well of one anothers' skill in business and resolved to open up a store together.  As ill luck would have it, Ivan was quite absent-minded and he threw out a large amount of cash.  This annoyed Boris who therefore demanded that Ivan have nothing to do with the monetary matters of their new store.  Later, however, Ivan redeemed himself by selling his fancy new stereo set to replace the lost cash.

Now consider two more stories:

Story A: John and Christine loved each other and decided to be married.  Unfortunately, Christine was so reckless that she accidently dented John's new car.  This upset John, so he insisted that she never drive his car again.

Story B: John and Christine loved each other and decided to be married.  Unfortunately, John discovered that Christine was a very reckless driver.  So he insisted that Christine never drive his new car.  This upset Christine so much that she dented John's new car hoping that John would be hurt.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 10 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1: Two small countries, Bolon and Salam, were adjacent to a large, warlike country called Mayonia.
Bolon decided to make the best of the situation by taking over Salam. Salam started looking for aid from other strong countries but soon Bolon succeeded in taking it over.
Then victorious Bolon proposed to make a treaty with its warlike neighbor Mayonia. Bolon proposed to give Mayonia control over Salam in exchange for a guarantee that Bolon would remain independent.
Mayonia responded by overrunning both Bolon and Salam. Bolon was so busy maintaining control of Salam, it could do nothing to stop Mayonia. Therupon, Mayonia installed puppet governments in both Bolon and Salam, and took over the newspapers and radio stations.

Now consider two more stories:

Story A: Two seventh graders, Lincoln and Moreland, were walking to school together when they met Chad. Chad was a mean high school boy who was known to rob younger kids.Moreland was scared but he decided to make the best of the situation by offering to help Chad rob Lincoln in exchange for being left alone himself.
But Lincoln overheard and started running to find a policeman. Immediately, Moreland took off after him and eventually succeeded in catching him.
When Chad arrived he robbed both of them. And Moreland was so exhausted, he could do nothing to prevent it.

Story B: Two sixth-grade boys, Lincoln and Moreland were walking to school together when they met Chad. Chad was a mean high school boy who was known to rob younger kids.
Moreland was scared but he decided to make the best of the situation by overpowering Lincoln. Immediately, Lincoln started running to find a policeman but Moreland ran after Lincoln and eventually succeeded in catching him.
When Chad arrived Moreland offered to let him rob Lincoln in exchange for being left alone himself. But Chad robbed both of them. Moreland was so busy holding Lincoln down, he could do nothing to prevent it.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 11 of 18...
True analogy vs. false analogy

Consider the following story:

Story 1:      A farmer named Beedle had a choice apricot tree that he valued above all the rest in his garden.  Every year Beedle gave presents of fruit from this tree to everyone he knew.
     But one year the tree began to wither and there was no moreof the wonderful fruit.  Everyone was very unhappy.
     The judge had enjoyed the apricots from the tree very much -so much so that he resolved to take the tree to his own garden to take care of it.   He paid Beedle very well and had the tree moved to his own grounds.  Fortunately, as soon as it was transplanted, the tree bore delicious apricots again.  That very year, the fruit won first prize in the county fair.

Now consider two more stories:

Story A:      Mr. Gerson had several pets but he valued the canary above all the rest.  Occasionally, he invited friends over to hear the canary sing.
     A wealthy businessman liked the canary's songs so much that one autumn he decided he wanted the bird in his house in the city where he could enjoy it every day.  He paid Mr. Gerson very well and had the canary moved to his house.
     However, upon being moved the canary became fatally ill and there were no more of its beautiful songs.  Everyone was extremely disappointed.

Story B:      Mr. Gerson had several pets but he valued the canary above all the rest.  Occasionally, he invited friends over to hear the canary sing.
     However, one autumn the canary became very ill and there were no more of its beautiful songs.   Everyone was extremely disappointed.
     A  veterinarian  friend  had liked the canary's songs  so much that he decided he would buy the canary and put it in his office where he could look after it.   He  paid  Mr. Gerson very well. Upon being moved, the canary sang beautiful songs again.

Which of Story A and Story B is a better analogy to Story 1? Is the best answer Story A, Story B, or both are equally analogous?
Source story 12 of 18...
True analogy vs. false analogy

Consider the following story:


In [48]:
# construct verbal analogies datasets from Webb et al
### verbal analogies ###
df = pd.read_excel (r'./../../../UCLA_VAT.xlsx', sheet_name='UCLA_VAT')
print(df.columns)
# Extract data
A = builtins.list(df['A'])
B = builtins.list(df['B'])
C = builtins.list(df['C'])
D = builtins.list(df['D'])
D_prime = builtins.list(df["D'"])

# Initialize storage for results
problem_types = []
pretexts = []
corrects = []
incorrects = []

# Evaluate 
N_prob = len(A)
prob_order = np.arange(N_prob)
np.random.shuffle(prob_order)
for p in range(N_prob):
	print(str(p+1) + ' of ' + str(N_prob) + '...')
	prompt = A[prob_order[p]] + ' : ' + B[prob_order[p]] + ' :: ' + C[prob_order[p]] + ' : '

	pretexts.append(prompt)
	corrects.append(D[prob_order[p]])
	incorrects.append(D_prime[prob_order[p]])
	problem_types.append(df["Relation"][prob_order[p]])
verbal_analogies_df = pd.DataFrame({
    'pretext': pretexts,
    'correct': corrects,
    'incorrect': incorrects,
    # 'problem_type': problem_types
})

Index(['Relation', 'A', 'B', 'C', 'D', 'D''], dtype='object')
1 of 80...
2 of 80...
3 of 80...
4 of 80...
5 of 80...
6 of 80...
7 of 80...
8 of 80...
9 of 80...
10 of 80...
11 of 80...
12 of 80...
13 of 80...
14 of 80...
15 of 80...
16 of 80...
17 of 80...
18 of 80...
19 of 80...
20 of 80...
21 of 80...
22 of 80...
23 of 80...
24 of 80...
25 of 80...
26 of 80...
27 of 80...
28 of 80...
29 of 80...
30 of 80...
31 of 80...
32 of 80...
33 of 80...
34 of 80...
35 of 80...
36 of 80...
37 of 80...
38 of 80...
39 of 80...
40 of 80...
41 of 80...
42 of 80...
43 of 80...
44 of 80...
45 of 80...
46 of 80...
47 of 80...
48 of 80...
49 of 80...
50 of 80...
51 of 80...
52 of 80...
53 of 80...
54 of 80...
55 of 80...
56 of 80...
57 of 80...
58 of 80...
59 of 80...
60 of 80...
61 of 80...
62 of 80...
63 of 80...
64 of 80...
65 of 80...
66 of 80...
67 of 80...
68 of 80...
69 of 80...
70 of 80...
71 of 80...
72 of 80...
73 of 80...
74 of 80...
75 of 80...
76 of 80...
77 of 80...
78 of 80...
79 of 80...
80 of 80...

In [ ]:
# verbal_analogies_df.to_csv("../../behavioral_eval_stimuli/log_p_curated/verbal_analogies.csv", index=False)

In [60]:
# construct an MC version of the entity tracking dataset by Kim and Schuster
import json
import csv
import random
import re
from pathlib import Path

INPUT_PATH = "../../../boxes-dataset-v1/few_shot_boxes_nso_exp2_max3/test-subsample-states-t5.jsonl"
OUTPUT_PATH = "../../behavioral_eval_stimuli/log_p_curated/multiple_choice_entity_tracking.csv"
NUM_INCORRECT = 5  # number of distractor options per example
MASK_TOKEN = "<extra_id_0>"  # assumed masking prefix

PROMPT_TEMPLATE = """Given the description after "Description:", write a true statement about all boxes and their contents according to the description after "Statement:". Format the statement as Box 0 contains the A, Box 1 contains the B, Box 2 contains the C, Box 3 contains the D, Box 4 contains the E, Box 5 contains the F, Box 6 contains the G. A, B, C, D, E, F, G are placeholders for the contents of each box.

Description: {desc}"""
ANSWER_TEMPLATE = "\nStatement: {answer}"

def extract_description(full_input):
    """
    Extract description text before the masking token.
    """
    if MASK_TOKEN in full_input:
        desc = full_input.split(MASK_TOKEN)[0].strip()
        answer = full_input.split(".")[-2].strip().replace(MASK_TOKEN, "").strip()
    else:
        desc = full_input.strip()
        answer = full_input.split(".")[-2].strip()
    return desc, answer


def extract_objects_from_text(text):
    """
    Extract candidate object nouns from description using simple regex.
    Assumes objects appear as 'the X' or standalone nouns.
    """
    # Capture words after 'the'
    candidates = re.findall(r"\bthe ([a-zA-Z\-]+)", text)
    print("--- candidates ---- ", candidates)
    # Remove duplicates
    return list(set(candidates))


def parse_correct_statement(statement):
    """
    Parse correct answer into a list of box contents.
    Returns list of strings per box.
    """
    boxes = re.findall(r"Box \d+ contains ([^,]+(?:,?\.[^B]*)?)", statement)
    boxes = [b.split(".")[0] for b in boxes]
    print("boxes : ----", boxes)
    return [b.strip() for b in boxes]


def generate_incorrect_options(objects, num_boxes, true_statement):
    """
    Generate incorrect full statements by randomly assigning
    objects across boxes.
    """
    incorrect_options = set()

    # Ensure enough objects for sampling
    if len(objects) == 0:
        return []

    while len(incorrect_options) < NUM_INCORRECT:
        shuffled = objects[:]
        random.shuffle(shuffled)

        # Random partition of objects across boxes
        partitions = []
        idx = 0
        for _ in range(num_boxes):
            # Random 0-2 objects per box
            k = random.randint(0, min(2, len(shuffled) - idx))
            contents = shuffled[idx:idx + k]
            idx += k
            if contents:
                partitions.append(" and ".join(f"the {o}" for o in contents))
            else:
                partitions.append("nothing")

        candidate = ", ".join(
            f"{partitions[i]}"
            for i in range(num_boxes)
        )

        if candidate != true_statement:
            incorrect_options.add(candidate)

    return list(incorrect_options)


def main():
    rows = []
    num_samples = 0
    with open(INPUT_PATH, "r") as f:
        # take the first 670 examples 
        for line in f:
            sample = json.loads(line)
            if num_samples >= 670:
                break
            num_samples += 1

            full_input = sample["sentence_masked"]
            print("full input", full_input)
            correct = sample["masked_content"].replace(MASK_TOKEN, "").strip() + "."
            print("correct ", correct)
            desc, answer = extract_description(full_input)
            target_box_number = re.findall(r"\d+", answer)
            print("-- answer and extracted target box number: ---- ", answer, target_box_number)
            context = PROMPT_TEMPLATE.format(desc=desc)
            answer_prefix = ANSWER_TEMPLATE.format(answer=answer)
            objects = extract_objects_from_text(desc)
            print("-- extracted objects: ", objects)
            box_contents = parse_correct_statement(desc)
            print("box contents : ----", box_contents)
            num_boxes = len(box_contents)
            print("num boxes : ----", num_boxes)
            # use the contents of non-target boxes as incorrect options
            incorrect = [f"{content}." for i, content in enumerate(box_contents) if i != target_box_number]
            incorrect_filtered = [i for i in incorrect if i != correct]
            incorrect_samples = np.random.choice(incorrect_filtered, size=min(num_boxes-1, len(incorrect_filtered)), replace=False).tolist()
            print(len(incorrect_samples), "incorrect options generated from non-target boxes: ", incorrect_samples)
            # incorrect = generate_incorrect_options(
            #     objects, num_boxes, correct
            # )

            rows.append({
                "context": context + answer_prefix,
                "correct": correct,
                "incorrect": incorrect_samples
            })

    with open(OUTPUT_PATH, "w", newline="") as csvfile:
        writer = csv.DictWriter(
            csvfile,
            fieldnames=["context", "correct", "incorrect"]
        )
        writer.writeheader()
        writer.writerows(rows)

    print(f"Saved to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()

full input Box 0 contains the boat and the shoe and the television, Box 1 contains the camera and the car and the plane, Box 2 contains the cake, Box 3 contains the fan, Box 4 contains the cross and the file and the note, Box 5 contains the chemical, Box 6 contains nothing. Move the cake from Box 2 to Box 6. Put the dish and the stone into Box 5. Move the television from Box 0 to Box 6. Put the drink into Box 2. Move the chemical and the stone from Box 5 to Box 2. Box 0 contains <extra_id_0> .
correct  the boat and the shoe.
-- answer and extracted target box number: ----  Box 0 contains ['0']
--- candidates ----  ['boat', 'shoe', 'television', 'camera', 'car', 'plane', 'cake', 'fan', 'cross', 'file', 'note', 'chemical', 'cake', 'dish', 'stone', 'television', 'drink', 'chemical', 'stone']
-- extracted objects:  ['cake', 'chemical', 'stone', 'drink', 'cross', 'television', 'file', 'note', 'dish', 'shoe', 'plane', 'car', 'fan', 'camera', 'boat']
boxes : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
box contents : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['the cake.', 'the camera and the car and the plane.', 'the cross and the file and the note.', 'the fan.', 'the boat and the shoe and the television.', 'nothing.']
full input Box 0 contains the boat and the shoe and the television, Box 1 contains the camera and the car and the plane, Box 2 contains the cake, Box 3 contains the fan, Box 4 contains the cross and the file and the note, Box 5 contains the chemical, Box 6 contains nothing. Move the cake from Box 2 to Box 6. Put the dish and the stone into Box 5. Move the television from Box 0 to Box 6. Put the drink into Box 2. Move the chemical and the stone from Box 5 to Box 2. Box 1 contains <extra_id_0> .
correct  the camera and the car and the plane.
-- answer and extracted target box number: ----  Box 1 contains ['1']
--- candidates ----  ['boat', 'shoe', 'television', 'camera', 'car', 'plane', 'cake', 'fan', 'cross', 'file', 'note', 'chemical', 'cake', 'dish', 'stone', 'television', 'drink', 'chemical', 'stone']
-- extracted objects:  ['cake', 'chemical', 'stone', 'drink', 'cross', 'television', 'file', 'note', 'dish', 'shoe', 'plane', 'car', 'fan', 'camera', 'boat']
boxes : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
box contents : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['the fan.', 'the cake.', 'the chemical.', 'the cross and the file and the note.', 'nothing.', 'the boat and the shoe and the television.']
full input Box 0 contains the boat and the shoe and the television, Box 1 contains the camera and the car and the plane, Box 2 contains the cake, Box 3 contains the fan, Box 4 contains the cross and the file and the note, Box 5 contains the chemical, Box 6 contains nothing. Move the cake from Box 2 to Box 6. Put the dish and the stone into Box 5. Move the television from Box 0 to Box 6. Put the drink into Box 2. Move the chemical and the stone from Box 5 to Box 2. Box 2 contains <extra_id_0> .
correct  the chemical and the drink and the stone.
-- answer and extracted target box number: ----  Box 2 contains ['2']
--- candidates ----  ['boat', 'shoe', 'television', 'camera', 'car', 'plane', 'cake', 'fan', 'cross', 'file', 'note', 'chemical', 'cake', 'dish', 'stone', 'television', 'drink', 'chemical', 'stone']
-- extracted objects:  ['cake', 'chemical', 'stone', 'drink', 'cross', 'television', 'file', 'note', 'dish', 'shoe', 'plane', 'car', 'fan', 'camera', 'boat']
boxes : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
box contents : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['the camera and the car and the plane.', 'the cake.', 'the cross and the file and the note.', 'nothing.', 'the boat and the shoe and the television.', 'the fan.']
full input Box 0 contains the boat and the shoe and the television, Box 1 contains the camera and the car and the plane, Box 2 contains the cake, Box 3 contains the fan, Box 4 contains the cross and the file and the note, Box 5 contains the chemical, Box 6 contains nothing. Move the cake from Box 2 to Box 6. Put the dish and the stone into Box 5. Move the television from Box 0 to Box 6. Put the drink into Box 2. Move the chemical and the stone from Box 5 to Box 2. Box 3 contains <extra_id_0> .
correct  the fan.
-- answer and extracted target box number: ----  Box 3 contains ['3']
--- candidates ----  ['boat', 'shoe', 'television', 'camera', 'car', 'plane', 'cake', 'fan', 'cross', 'file', 'note', 'chemical', 'cake', 'dish', 'stone', 'television', 'drink', 'chemical', 'stone']
-- extracted objects:  ['cake', 'chemical', 'stone', 'drink', 'cross', 'television', 'file', 'note', 'dish', 'shoe', 'plane', 'car', 'fan', 'camera', 'boat']
boxes : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
box contents : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['nothing.', 'the cake.', 'the chemical.', 'the boat and the shoe and the television.', 'the camera and the car and the plane.', 'the cross and the file and the note.']
full input Box 0 contains the boat and the shoe and the television, Box 1 contains the camera and the car and the plane, Box 2 contains the cake, Box 3 contains the fan, Box 4 contains the cross and the file and the note, Box 5 contains the chemical, Box 6 contains nothing. Move the cake from Box 2 to Box 6. Put the dish and the stone into Box 5. Move the television from Box 0 to Box 6. Put the drink into Box 2. Move the chemical and the stone from Box 5 to Box 2. Box 4 contains <extra_id_0> .
correct  the cross and the file and the note.
-- answer and extracted target box number: ----  Box 4 contains ['4']
--- candidates ----  ['boat', 'shoe', 'television', 'camera', 'car', 'plane', 'cake', 'fan', 'cross', 'file', 'note', 'chemical', 'cake', 'dish', 'stone', 'television', 'drink', 'chemical', 'stone']
-- extracted objects:  ['cake', 'chemical', 'stone', 'drink', 'cross', 'television', 'file', 'note', 'dish', 'shoe', 'plane', 'car', 'fan', 'camera', 'boat']
boxes : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
box contents : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['nothing.', 'the fan.', 'the boat and the shoe and the television.', 'the cake.', 'the chemical.', 'the camera and the car and the plane.']
full input Box 0 contains the boat and the shoe and the television, Box 1 contains the camera and the car and the plane, Box 2 contains the cake, Box 3 contains the fan, Box 4 contains the cross and the file and the note, Box 5 contains the chemical, Box 6 contains nothing. Move the cake from Box 2 to Box 6. Put the dish and the stone into Box 5. Move the television from Box 0 to Box 6. Put the drink into Box 2. Move the chemical and the stone from Box 5 to Box 2. Box 5 contains <extra_id_0> .
correct  the dish.
-- answer and extracted target box number: ----  Box 5 contains ['5']
--- candidates ----  ['boat', 'shoe', 'television', 'camera', 'car', 'plane', 'cake', 'fan', 'cross', 'file', 'note', 'chemical', 'cake', 'dish', 'stone', 'television', 'drink', 'chemical', 'stone']
-- extracted objects:  ['cake', 'chemical', 'stone', 'drink', 'cross', 'television', 'file', 'note', 'dish', 'shoe', 'plane', 'car', 'fan', 'camera', 'boat']
boxes : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
box contents : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['nothing.', 'the cross and the file and the note.', 'the fan.', 'the chemical.', 'the camera and the car and the plane.', 'the cake.']
full input Box 0 contains the boat and the shoe and the television, Box 1 contains the camera and the car and the plane, Box 2 contains the cake, Box 3 contains the fan, Box 4 contains the cross and the file and the note, Box 5 contains the chemical, Box 6 contains nothing. Move the cake from Box 2 to Box 6. Put the dish and the stone into Box 5. Move the television from Box 0 to Box 6. Put the drink into Box 2. Move the chemical and the stone from Box 5 to Box 2. Box 6 contains <extra_id_0> .
correct  the cake and the television.
-- answer and extracted target box number: ----  Box 6 contains ['6']
--- candidates ----  ['boat', 'shoe', 'television', 'camera', 'car', 'plane', 'cake', 'fan', 'cross', 'file', 'note', 'chemical', 'cake', 'dish', 'stone', 'television', 'drink', 'chemical', 'stone']
-- extracted objects:  ['cake', 'chemical', 'stone', 'drink', 'cross', 'television', 'file', 'note', 'dish', 'shoe', 'plane', 'car', 'fan', 'camera', 'boat']
boxes : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
box contents : ---- ['the boat and the shoe and the television', 'the camera and the car and the plane', 'the cake', 'the fan', 'the cross and the file and the note', 'the chemical', 'nothing']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['the cross and the file and the note.', 'the camera and the car and the plane.', 'the chemical.', 'the fan.', 'the cake.', 'the boat and the shoe and the television.']
full input Box 0 contains the cash and the ticket, Box 1 contains nothing, Box 2 contains the beer and the brain and the guitar, Box 3 contains the medicine and the newspaper, Box 4 contains the crown, Box 5 contains the ice and the painting, Box 6 contains the bomb and the boot and the plane. Put the meat into Box 5. Move the ticket from Box 0 to Box 1. Remove the newspaper from Box 3. Remove the guitar from Box 2. Remove the brain from Box 2. Remove the beer from Box 2. Move the ticket from Box 1 to Box 3. Move the medicine from Box 3 to Box 2. Move the cash from Box 0 to Box 3. Box 0 contains <extra_id_0> .
correct  nothing.
-- answer and extracted target box number: ----  Box 0 contains ['0']
--- candidates ----  ['cash', 'ticket', 'beer', 'brain', 'guitar', 'medicine', 'newspaper', 'crown', 'ice', 'painting', 'bomb', 'boot', 'plane', 'meat', 'ticket', 'newspaper', 'guitar', 'brain', 'beer', 'ticket', 'medicine', 'cash']
-- extracted objects:  ['cash', 'guitar', 'brain', 'ticket', 'medicine', 'boot', 'painting', 'ice', 'meat', 'plane', 'beer', 'newspaper', 'crown', 'bomb']
boxes : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
box contents : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['the beer and the brain and the guitar.', 'the cash and the ticket.', 'the ice and the painting.', 'the medicine and the newspaper.', 'the bomb and the boot and the plane.', 'the crown.']
full input Box 0 contains the cash and the ticket, Box 1 contains nothing, Box 2 contains the beer and the brain and the guitar, Box 3 contains the medicine and the newspaper, Box 4 contains the crown, Box 5 contains the ice and the painting, Box 6 contains the bomb and the boot and the plane. Put the meat into Box 5. Move the ticket from Box 0 to Box 1. Remove the newspaper from Box 3. Remove the guitar from Box 2. Remove the brain from Box 2. Remove the beer from Box 2. Move the ticket from Box 1 to Box 3. Move the medicine from Box 3 to Box 2. Move the cash from Box 0 to Box 3. Box 1 contains <extra_id_0> .
correct  nothing.
-- answer and extracted target box number: ----  Box 1 contains ['1']
--- candidates ----  ['cash', 'ticket', 'beer', 'brain', 'guitar', 'medicine', 'newspaper', 'crown', 'ice', 'painting', 'bomb', 'boot', 'plane', 'meat', 'ticket', 'newspaper', 'guitar', 'brain', 'beer', 'ticket', 'medicine', 'cash']
-- extracted objects:  ['cash', 'guitar', 'brain', 'ticket', 'medicine', 'boot', 'painting', 'ice', 'meat', 'plane', 'beer', 'newspaper', 'crown', 'bomb']
boxes : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
box contents : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['the medicine and the newspaper.', 'the beer and the brain and the guitar.', 'the bomb and the boot and the plane.', 'the ice and the painting.', 'the crown.', 'the cash and the ticket.']
full input Box 0 contains the cash and the ticket, Box 1 contains nothing, Box 2 contains the beer and the brain and the guitar, Box 3 contains the medicine and the newspaper, Box 4 contains the crown, Box 5 contains the ice and the painting, Box 6 contains the bomb and the boot and the plane. Put the meat into Box 5. Move the ticket from Box 0 to Box 1. Remove the newspaper from Box 3. Remove the guitar from Box 2. Remove the brain from Box 2. Remove the beer from Box 2. Move the ticket from Box 1 to Box 3. Move the medicine from Box 3 to Box 2. Move the cash from Box 0 to Box 3. Box 2 contains <extra_id_0> .
correct  the medicine.
-- answer and extracted target box number: ----  Box 2 contains ['2']
--- candidates ----  ['cash', 'ticket', 'beer', 'brain', 'guitar', 'medicine', 'newspaper', 'crown', 'ice', 'painting', 'bomb', 'boot', 'plane', 'meat', 'ticket', 'newspaper', 'guitar', 'brain', 'beer', 'ticket', 'medicine', 'cash']
-- extracted objects:  ['cash', 'guitar', 'brain', 'ticket', 'medicine', 'boot', 'painting', 'ice', 'meat', 'plane', 'beer', 'newspaper', 'crown', 'bomb']
boxes : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
box contents : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['nothing.', 'the cash and the ticket.', 'the beer and the brain and the guitar.', 'the ice and the painting.', 'the bomb and the boot and the plane.', 'the crown.']
full input Box 0 contains the cash and the ticket, Box 1 contains nothing, Box 2 contains the beer and the brain and the guitar, Box 3 contains the medicine and the newspaper, Box 4 contains the crown, Box 5 contains the ice and the painting, Box 6 contains the bomb and the boot and the plane. Put the meat into Box 5. Move the ticket from Box 0 to Box 1. Remove the newspaper from Box 3. Remove the guitar from Box 2. Remove the brain from Box 2. Remove the beer from Box 2. Move the ticket from Box 1 to Box 3. Move the medicine from Box 3 to Box 2. Move the cash from Box 0 to Box 3. Box 3 contains <extra_id_0> .
correct  the cash and the ticket.
-- answer and extracted target box number: ----  Box 3 contains ['3']
--- candidates ----  ['cash', 'ticket', 'beer', 'brain', 'guitar', 'medicine', 'newspaper', 'crown', 'ice', 'painting', 'bomb', 'boot', 'plane', 'meat', 'ticket', 'newspaper', 'guitar', 'brain', 'beer', 'ticket', 'medicine', 'cash']
-- extracted objects:  ['cash', 'guitar', 'brain', 'ticket', 'medicine', 'boot', 'painting', 'ice', 'meat', 'plane', 'beer', 'newspaper', 'crown', 'bomb']
boxes : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
box contents : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['nothing.', 'the bomb and the boot and the plane.', 'the crown.', 'the ice and the painting.', 'the beer and the brain and the guitar.', 'the medicine and the newspaper.']
full input Box 0 contains the cash and the ticket, Box 1 contains nothing, Box 2 contains the beer and the brain and the guitar, Box 3 contains the medicine and the newspaper, Box 4 contains the crown, Box 5 contains the ice and the painting, Box 6 contains the bomb and the boot and the plane. Put the meat into Box 5. Move the ticket from Box 0 to Box 1. Remove the newspaper from Box 3. Remove the guitar from Box 2. Remove the brain from Box 2. Remove the beer from Box 2. Move the ticket from Box 1 to Box 3. Move the medicine from Box 3 to Box 2. Move the cash from Box 0 to Box 3. Box 4 contains <extra_id_0> .
correct  the crown.
-- answer and extracted target box number: ----  Box 4 contains ['4']
--- candidates ----  ['cash', 'ticket', 'beer', 'brain', 'guitar', 'medicine', 'newspaper', 'crown', 'ice', 'painting', 'bomb', 'boot', 'plane', 'meat', 'ticket', 'newspaper', 'guitar', 'brain', 'beer', 'ticket', 'medicine', 'cash']
-- extracted objects:  ['cash', 'guitar', 'brain', 'ticket', 'medicine', 'boot', 'painting', 'ice', 'meat', 'plane', 'beer', 'newspaper', 'crown', 'bomb']
boxes : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
box contents : ---- ['the cash and the ticket', 'nothing', 'the beer and the brain and the guitar', 'the medicine and the newspaper', 'the crown', 'the ice and the painting', 'the bomb and the boot and the plane']
num boxes : ---- 7
6 incorrect options generated from non-target boxes:  ['the cash and the ticket.', 'the beer and the brain and the guitar.', 'nothing.', 'the bomb and the boot and the plane.', 'the medicine and the newspaper.', 'the ice and the painting.']

In [67]:
# cast into long format
tracker_df_wide = pd.read_csv(OUTPUT_PATH)
tracker_df_wide

,context,correct,incorrect
0,"Given the description after ""Description:"", wr...",the boat and the shoe.,"['the cake.', 'the camera and the car and the ..."
1,"Given the description after ""Description:"", wr...",the camera and the car and the plane.,"['the fan.', 'the cake.', 'the chemical.', 'th..."
2,"Given the description after ""Description:"", wr...",the chemical and the drink and the stone.,"['the camera and the car and the plane.', 'the..."
3,"Given the description after ""Description:"", wr...",the fan.,"['nothing.', 'the cake.', 'the chemical.', 'th..."
4,"Given the description after ""Description:"", wr...",the cross and the file and the note.,"['nothing.', 'the fan.', 'the boat and the sho..."
...,...,...,...
665,"Given the description after ""Description:"", wr...",nothing.,"['the pipe and the plate and the rock.', 'the ..."
666,"Given the description after ""Description:"", wr...",the plant.,"['the apple and the bell and the crown.', 'the..."
667,"Given the description after ""Description:"", wr...",nothing.,"['the apple and the bell and the crown.', 'the..."
668,"Given the description after ""Description:"", wr...",the branch and the document and the map.,"['nothing.', 'nothing.', 'the pipe and the pla..."
669,"Given the description after ""Description:"", wr...",the pipe and the plate and the rock.,"['the painting.', 'the plant.', 'the magazine...."

In [68]:
# split and clean the options in incorrect
tracker_df_wide['incorrect_clean'] = tracker_df_wide.apply(lambda x: x['incorrect'].replace("[", "").replace("]", "").replace("'", "").strip().split(", "), axis=1)

In [70]:
tracker_df_long = tracker_df_wide.explode(
    'incorrect_clean'
)

In [73]:
tracker_df_long["id"] = tracker_df_long.index

In [76]:
tracker_df_long_selected = tracker_df_long[["id", "context", "correct", "incorrect_clean"]]

In [78]:
tracker_df_long_selected = tracker_df_long_selected.rename(columns={
    "context": "pretext",
    "incorrect_clean": "incorrect"
})

In [ ]:
# tracker_df_long_selected.to_csv("../../behavioral_eval_stimuli/log_p_curated/entity_tracking.csv", index=False)